/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/hajj/kaaba.glb 
Author: agrees_putra (https://sketchfab.com/agrees_putra)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kaaba-in-mecca-43041d42a0ae4cb58e20a86edc572688
Title: Kaaba in Mecca
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/kaaba.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.007}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[0, 763.448, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={637.421}>
            <mesh geometry={nodes.Cube_Kabaa_Marble_0.geometry} material={materials.Kabaa_Marble} />
            <mesh geometry={nodes.Cube_Kabaa_Wall_0.geometry} material={materials.Kabaa_Wall} />
            <mesh geometry={nodes.Cube_Kabaa_Brick_0.geometry} material={materials.Kabaa_Brick} />
            <mesh geometry={nodes.Cube_Kabaa_Door_0.geometry} material={materials.Kabaa_Door} />
          </group>
          <group position={[-666.244, 222.461, 666.352]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={103.226}>
            <mesh geometry={nodes.Sphere_Hajjar_Aswad_0.geometry} material={materials.Hajjar_Aswad} />
            <mesh geometry={nodes.Sphere_Hajjar_Aswad_Metal_0.geometry} material={materials.Hajjar_Aswad_Metal} />
          </group>
          <group position={[1116.216, 126.027, -0.51]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[637.421, 637.421, 127.484]}>
            <group position={[0, -0.922, -0.203]} scale={[0.062, 0.062, 0.311]}>
              <mesh geometry={nodes.Circle_Material003_0.geometry} material={materials['Material.003']} />
              <mesh geometry={nodes.Circle_Material002_0.geometry} material={materials['Material.002']} />
            </group>
            <group position={[-0.834, -0.349, -0.203]} scale={[0.062, 0.062, 0.311]}>
              <mesh geometry={nodes.Circle001_Material003_0.geometry} material={materials['Material.003']} />
              <mesh geometry={nodes.Circle001_Material002_0.geometry} material={materials['Material.002']} />
            </group>
            <group position={[0.828, -0.349, -0.203]} scale={[0.062, 0.062, 0.311]}>
              <mesh geometry={nodes.Circle002_Material003_0.geometry} material={materials['Material.003']} />
              <mesh geometry={nodes.Circle002_Material002_0.geometry} material={materials['Material.002']} />
            </group>
            <mesh geometry={nodes.Cylinder004_Material001_0.geometry} material={materials['Material.001']} />
          </group>
          <group position={[720.57, 1244.76, 0]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[26.196, 87.32, 87.32]}>
            <mesh geometry={nodes.Plane001_Golden_Gutter_0.geometry} material={materials.Golden_Gutter} />
            <mesh geometry={nodes.Plane001_Golden_Gutter_front_0.geometry} material={materials.Golden_Gutter_front} />
          </group>
          <group position={[70.478, 347.473, 1609.238]} rotation={[-Math.PI / 2, 0, 0]} scale={24.207}>
            <mesh geometry={nodes.Sphere001_Material005_0.geometry} material={materials['Material.005']} />
            <mesh geometry={nodes.Sphere001_Material006_0.geometry} material={materials['Material.006']} />
            <mesh geometry={nodes.Sphere001_SoI_Marble_Yellow_0.geometry} material={materials.SoI_Marble_Yellow} />
            <mesh geometry={nodes.Sphere001_SoI_Marble_Green_0.geometry} material={materials.SoI_Marble_Green} />
            <mesh geometry={nodes.Sphere001_SoI_Marble_Black_0.geometry} material={materials.SoI_Marble_Black} />
            <mesh geometry={nodes.Sphere001_SoI_ornament_0.geometry} material={materials.SoI_ornament} />
          </group>
          <group position={[0, 763.448, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={637.421}>
            <mesh geometry={nodes.Cube006_wall_inside002_0.geometry} material={materials['wall_inside.002']} />
            <mesh geometry={nodes.Cube006_wall_green_top_0.geometry} material={materials.wall_green_top} />
          </group>
          <group position={[-356.867, 394.047, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[48.734, 48.734, 19.494]}>
            <mesh geometry={nodes.Cube009_gold001_0.geometry} material={materials['gold.001']} />
            <mesh geometry={nodes.Cube009_pillar_0.geometry} material={materials.pillar} />
          </group>
          <group position={[0, 394.047, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[48.734, 48.734, 19.494]}>
            <mesh geometry={nodes.Cube010_gold001_0.geometry} material={materials['gold.001']} />
            <mesh geometry={nodes.Cube010_pillar_0.geometry} material={materials.pillar} />
          </group>
          <group position={[357.802, 394.047, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[48.734, 48.734, 19.494]}>
            <mesh geometry={nodes.Cube011_gold001_0.geometry} material={materials['gold.001']} />
            <mesh geometry={nodes.Cube011_pillar_0.geometry} material={materials.pillar} />
          </group>
          <group position={[-163.459, 445.622, 70.5]} rotation={[Math.PI, 0, 0]} scale={[6.4, 6.4, 0.64]}>
            <mesh geometry={nodes.Cylinder005_gold002_0.geometry} material={materials['gold.002']} />
            <mesh geometry={nodes.Cylinder005_white_0.geometry} material={materials.white} />
            <mesh geometry={nodes.Cylinder005_grey_btm_0.geometry} material={materials.grey_btm} />
            <mesh geometry={nodes.Cylinder005_black_top_0.geometry} material={materials.black_top} />
            <mesh geometry={nodes.Cylinder005_plate_0.geometry} material={materials.plate} />
          </group>
          <group position={[-598.234, 756.752, 23.653]} rotation={[-Math.PI / 2, 0, 0]} scale={9.6}>
            <mesh geometry={nodes.Cylinder008_vase_gold_0.geometry} material={materials.vase_gold} />
            <mesh geometry={nodes.Cylinder008_vase_silver_0.geometry} material={materials.vase_silver} />
          </group>
          <mesh geometry={nodes.Cube001_Kabaa_Ornament_0.geometry} material={materials.Kabaa_Ornament} position={[0, 619.285, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={637.421} />
          <mesh geometry={nodes.Plane_Material_0.geometry} material={materials.Material} position={[-252.819, 874.153, 652.842]} scale={104.954} />
          <mesh geometry={nodes.Cylinder_Kabaa_ring_btm_0.geometry} material={materials.Kabaa_ring_btm} position={[-582.866, 123.146, 673.263]} rotation={[-1.162, Math.PI / 2, 0]} scale={[8.132, 8.132, 2.197]} />
          <mesh geometry={nodes.Cylinder001_Kabaa_ring_btm_0.geometry} material={materials.Kabaa_ring_btm} position={[621.923, 123.146, -673.994]} rotation={[1.162, -Math.PI / 2, 0]} scale={[8.132, 8.132, 2.197]} />
          <mesh geometry={nodes.Cylinder002_Kabaa_ring_btm_0.geometry} material={materials.Kabaa_ring_btm} position={[-670.798, 123.146, -602.76]} rotation={[0, 0, -1.162]} scale={[8.132, 8.132, 2.197]} />
          <mesh geometry={nodes.Cylinder003_Kabaa_ring_btm_0.geometry} material={materials.Kabaa_ring_btm} position={[676.459, 123.146, 602.029]} rotation={[-Math.PI, 0, 1.98]} scale={[8.132, 8.132, 2.197]} />
          <mesh geometry={nodes.Plane002_Material004_0.geometry} material={materials['Material.004']} position={[-1086.089, 1401.024, 1091.437]} rotation={[-Math.PI / 2, 0, -Math.PI / 4]} scale={[8.578, 637.421, 637.421]} />
          <mesh geometry={nodes.Cube003_Kabaa_Door_0.geometry} material={materials.Kabaa_Door} position={[-403.589, 652.973, 634.729]} rotation={[-Math.PI / 2, 0, 1.894]} scale={637.421} />
          <mesh geometry={nodes.Cube004_Kabaa_Door_0.geometry} material={materials.Kabaa_Door} position={[-104.726, 652.973, 634.729]} rotation={[-Math.PI / 2, 0, -0.441]} scale={637.421} />
          <mesh geometry={nodes.Cube005_floor_0.geometry} material={materials.floor} position={[0, 763.448, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={637.421} />
          <mesh geometry={nodes.Cube002__0.geometry} material={materials['Cube.002__0']} position={[480.708, 1327.455, 487.091]} rotation={[-Math.PI / 2, 0, 0]} scale={[100, 100, 30]} />
          <mesh geometry={nodes.Plane003_roof_inside_0.geometry} material={materials.roof_inside} position={[0, 1296.95, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={633.52} />
          <mesh geometry={nodes.Cube007_box_inside_0.geometry} material={materials.box_inside} position={[534.742, 829.376, 536.554]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[-100, 100, 471.206]} />
          <mesh geometry={nodes.Cube008_wall_btm_0.geometry} material={materials.wall_btm} position={[-198.771, 980.348, 626.971]} rotation={[-Math.PI / 2, 0, 0]} scale={10} />
          <mesh geometry={nodes.Cylinder006_ring_vase_0.geometry} material={materials.ring_vase} position={[0, 802.18, 22.159]} rotation={[Math.PI / 2, -Math.PI / 2, 0]} scale={[-2.207, 2.207, 635.323]} />
          <mesh geometry={nodes.Cylinder007_ring__0.geometry} material={materials.ring} position={[-369.847, 802.18, 19.063]} scale={[4, 4, 13.278]} />
          <mesh geometry={nodes.Cube012_gold_0.geometry} material={materials.gold} position={[415.99, 537.606, 551.977]} rotation={[Math.PI / 2, 0, -Math.PI]} scale={[-100, 100, 471.206]} />
          <mesh geometry={nodes.Cube013_floor_gold_0.geometry} material={materials.floor_gold} position={[120.142, 375.634, 235.839]} rotation={[-Math.PI / 2, 0, 0]} scale={9} />
          <mesh geometry={nodes.Cube014_wall_btm_0.geometry} material={materials.wall_btm} position={[120.142, 375.634, 235.839]} rotation={[-Math.PI / 2, 0, 0]} scale={9} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/kaaba.glb')
