/**
 * Script to add Urdu translations to ontology file 038.js (Surah Sad)
 */
import fs from 'fs';
import path from 'path';

const TRANSLATIONS = {
  meaning: {
    "The Letter Sad": "حرفِ صاد",
    "By the Quran full of remembrance": "قسم ہے قرآن کی جو ذکر والا ہے",
    "In pride and dissension": "تکبر اور مخالفت میں",
    "How many generations We destroyed before them": "ہم نے ان سے پہلے کتنی نسلیں تباہ کیں",
    "A magician, a liar": "جادوگر، جھوٹا",
    "Has he made the gods into one God?": "کیا اس نے سب معبودوں کو ایک معبود بنا دیا؟",
    "This is indeed an amazing thing": "یہ تو واقعی عجیب بات ہے",
    "Go and be patient upon your gods": "چلو اور اپنے معبودوں پر ثابت قدم رہو",
    "We never heard of this in the latest religion": "ہم نے یہ بات آخری دین میں نہیں سنی",
    "Or do they have the treasuries of your Lord's mercy?": "کیا ان کے پاس تیرے رب کی رحمت کے خزانے ہیں؟",
    "A small army there will be defeated from the confederates": "یہ مخالفین کا ایک لشکر ہے جو شکست کھائے گا",
    // previousNations
    "The people of Nuh denied before them": "ان سے پہلے نوح کی قوم نے جھٹلایا",
    "And Aad, and Pharaoh owner of stakes": "اور عاد اور فرعون میخوں والا",
    "And Thamud, Lut's people, and the people of the Thicket": "اور ثمود اور لوط کی قوم اور ایکہ والے",
    "Those are the confederates": "یہی مخالفین کے گروہ ہیں",
    "Each denied the messengers, so My punishment was justified": "سب نے رسولوں کو جھٹلایا تو میرا عذاب واجب ہو گیا",
    "These only await a single blast": "یہ صرف ایک چیخ کے منتظر ہیں",
    "Our Lord, hasten our share before the Day of Account": "اے ہمارے رب، حساب کے دن سے پہلے ہمارا حصہ جلدی دے دے",
    // dawudStory
    "Be patient over what they say": "جو وہ کہتے ہیں اس پر صبر کرو",
    "Remember Our servant Dawud, possessor of strength": "ہمارے بندے داؤد کو یاد کرو جو قوت والا تھا",
    "Indeed, he was one who repeatedly turned [to Allah]": "بے شک وہ بہت رجوع کرنے والا تھا",
    "We subjected the mountains with him": "ہم نے پہاڑوں کو اس کے ساتھ مسخر کیا",
    "Glorifying [Allah] in the evening and sunrise": "شام اور صبح تسبیح کرتے تھے",
    "And the birds assembled": "اور پرندے جمع تھے",
    "All were returning [to Allah in praise]": "سب اس کی طرف رجوع کرنے والے تھے",
    "And We strengthened his kingdom": "اور ہم نے اس کی سلطنت مضبوط کی",
    "And We gave him wisdom and decisive speech": "اور ہم نے اسے حکمت اور فیصلہ کن بات دی",
    "The news of the disputants when they climbed over the sanctuary wall": "جھگڑنے والوں کی خبر جب وہ محراب کی دیوار سے چڑھ آئے",
    "When they entered upon Dawud and he was alarmed by them": "جب وہ داؤد کے پاس آئے تو وہ ان سے گھبرا گیا",
    "Two disputants, one has wronged the other": "دو فریق، ایک نے دوسرے پر زیادتی کی",
    "This is my brother, he has ninety-nine ewes": "یہ میرا بھائی ہے، اس کی ننانوے دنبیاں ہیں",
    "And I have one ewe": "اور میری ایک دنبی ہے",
    "Give it to me": "وہ مجھے دے دے",
    "And he overpowered me in speech": "اور اس نے مجھ پر بات میں غلبہ پایا",
    "He has wronged you by demanding your ewe to add to his ewes": "اس نے تیری دنبی اپنی دنبیوں میں شامل کرنے کا مطالبہ کرکے تجھ پر ظلم کیا",
    "Indeed, many partners oppress one another": "بے شک بہت سے شراکت دار ایک دوسرے پر ظلم کرتے ہیں",
    "Except those who believe and do righteous deeds - and how few are they": "مگر وہ جو ایمان لائیں اور نیک عمل کریں - اور وہ کتنے کم ہیں",
    "And Dawud realized that We had tested him": "اور داؤد سمجھ گیا کہ ہم نے اسے آزمایا ہے",
    "So he asked forgiveness of his Lord and fell down bowing and turned in repentance": "تو اس نے اپنے رب سے مغفرت مانگی اور رکوع میں گر پڑا اور رجوع کیا",
    "So We forgave him that": "تو ہم نے اسے معاف کر دیا",
    "Indeed, he has nearness to Us and a good return": "بے شک اس کے لیے ہمارے پاس قربت اور اچھا ٹھکانا ہے",
    "O Dawud, We have made you a successor/ruler on earth": "اے داؤد، ہم نے تجھے زمین میں خلیفہ بنایا",
    "So judge between people with truth": "تو لوگوں کے درمیان حق کے ساتھ فیصلہ کرو",
    "And do not follow desire, lest it lead you astray from Allah's path": "اور خواہش کی پیروی نہ کرو ورنہ وہ تمہیں اللہ کے راستے سے بھٹکا دے گی",
    "Those who stray from Allah's path will have severe punishment": "جو اللہ کے راستے سے بھٹکتے ہیں ان کے لیے سخت عذاب ہے",
    "Because they forgot the Day of Account": "اس لیے کہ وہ حساب کا دن بھول گئے",
    // sulaymanStory
    "And We granted to Dawud, Sulayman": "اور ہم نے داؤد کو سلیمان عطا کیا",
    "Excellent is the servant; indeed, he was one repeatedly turning [to Allah]": "کیا اچھا بندہ ہے، بے شک وہ بہت رجوع کرنے والا تھا",
    "When there were displayed before him in the evening the poised horses": "جب شام کو اس کے سامنے عمدہ تیز گھوڑے پیش کیے گئے",
    "Indeed, I loved the love of good [things] over the remembrance of my Lord": "میں نے نیکی کی محبت کو اپنے رب کی یاد پر ترجیح دے دی",
    "Until [the sun] disappeared behind the veil [of the horizon]": "یہاں تک کہ (سورج) پردے میں چھپ گیا",
    "Return them to me": "انہیں میرے پاس واپس لاؤ",
    "And he began to pass his hand over their legs and necks": "اور اس نے ان کی ٹانگوں اور گردنوں پر ہاتھ پھیرنا شروع کیا",
    "And We certainly tested Sulayman": "اور ہم نے سلیمان کو ضرور آزمایا",
    "And We placed on his throne a body": "اور ہم نے اس کے تخت پر ایک جسد رکھ دیا",
    "Then he turned back [to Allah]": "پھر اس نے رجوع کیا",
    "He said: My Lord, forgive me and grant me a kingdom": "اس نے کہا: میرے رب، مجھے معاف کر اور مجھے ایسی سلطنت دے",
    "Such as will not belong to anyone after me": "جو میرے بعد کسی کو نہ ملے",
    "Indeed, You are the Bestower": "بے شک تو بہت عطا کرنے والا ہے",
    "So We subjected to him the wind, blowing by his command": "تو ہم نے اس کے لیے ہوا مسخر کر دی جو اس کے حکم سے چلتی تھی",
    "Gently wherever he directed": "نرمی سے جہاں وہ چاہتا",
    "And the devils - every builder and diver": "اور شیاطین - ہر معمار اور غوطہ خور",
    "And others bound together in chains": "اور دوسرے زنجیروں میں جکڑے ہوئے",
    "This is Our gift, so grant or withhold without account": "یہ ہمارا عطیہ ہے، چاہو تو دو یا روکو، بے حساب ہے",
    "And indeed, for him is nearness to Us and a good return": "اور بے شک اس کے لیے ہمارے پاس قربت اور اچھا ٹھکانا ہے",
    // ayyubStory
    "And remember Our servant Ayyub": "اور ہمارے بندے ایوب کو یاد کرو",
    "When he called to his Lord: Satan has touched me with hardship and torment": "جب اس نے اپنے رب کو پکارا: شیطان نے مجھے تکلیف اور عذاب میں مبتلا کیا",
    "Strike with your foot": "اپنا پاؤں مارو",
    "This is a cool spring for bathing and drinking": "یہ نہانے اور پینے کا ٹھنڈا پانی ہے",
    "And We granted him his family and the like of them with them": "اور ہم نے اسے اس کا گھرانا اور اتنے ہی اور ان کے ساتھ دے دیے",
    "As mercy from Us and a reminder for those of understanding": "ہماری طرف سے رحمت اور عقلمندوں کے لیے یاد دہانی",
    "And take in your hand a bunch [of grass]": "اور اپنے ہاتھ میں ایک مٹھی (گھاس) لو",
    "Strike with it and do not break your oath": "اس سے مارو اور قسم نہ توڑو",
    "Indeed, We found him patient": "بے شک ہم نے اسے صبر کرنے والا پایا",
    // otherProphets
    "And remember Our servants Ibrahim, Ishaq, and Ya'qub": "اور ہمارے بندوں ابراہیم، اسحاق اور یعقوب کو یاد کرو",
    "Possessors of strength and vision": "قوت اور بصیرت والے",
    "We chose them for an exclusive quality - remembrance of the [final] abode": "ہم نے انہیں ایک خالص صفت کے لیے چنا - آخرت کی یاد",
    "And indeed they are, to Us, among the chosen, the outstanding": "اور بے شک وہ ہمارے نزدیک چنیدہ اور بہترین میں سے ہیں",
    "And remember Ismail, Elisha, and Dhul-Kifl": "اور اسماعیل، الیسع اور ذوالکفل کو یاد کرو",
    "And all are among the outstanding": "اور سب بہترین لوگوں میں سے ہیں",
    // paradiseDescription
    "This is a reminder": "یہ ایک یاد دہانی ہے",
    "And indeed, for the righteous is a good return": "اور بے شک متقیوں کے لیے اچھا ٹھکانا ہے",
    "Gardens of perpetual residence, with doors opened for them": "ہمیشہ رہنے کے باغات، ان کے لیے دروازے کھلے ہوئے",
    "Reclining therein, calling for much fruit and drink": "اس میں تکیہ لگائے بیٹھے، بہت سے پھلوں اور مشروبات کی فرمائش کرتے ہوئے",
    "And with them will be women limiting their glances, of equal age": "اور ان کے پاس نگاہیں جھکائے ہم عمر عورتیں ہوں گی",
    "This is what you are promised for the Day of Account": "یہ ہے جس کا تم سے حساب کے دن کا وعدہ کیا جاتا ہے",
    "Indeed, this is Our provision, for it there is no depletion": "بے شک یہ ہمارا رزق ہے جو کبھی ختم نہ ہوگا",
    // hellfireDescription
    "This [is so]. And for the transgressors is an evil return": "یہ (ایسا ہے)۔ اور سرکشوں کے لیے بُرا ٹھکانا ہے",
    "Hell, which they will burn": "جہنم جس میں وہ جلیں گے",
    "Wretched is the resting place": "کیا بُرا بستر ہے",
    "This - so let them taste it - is scalding water and [foul] discharge": "یہ ہے - چکھیں اسے - کھولتا پانی اور پیپ",
    "And other [punishments] of its kind in pairs": "اور اسی قسم کے اور جوڑے دار عذاب",
    "This is a company bursting in with you": "یہ ایک جماعت ہے جو تمہارے ساتھ گھسی آ رہی ہے",
    "No welcome for them": "ان کے لیے کوئی خوش آمدید نہیں",
    "Indeed, they will burn in the Fire": "بے شک وہ آگ میں جلیں گے",
    "They said: No, it is you - no welcome for you": "انہوں نے کہا: نہیں، تمہیں خوش آمدید نہیں",
    "You presented this to us": "تم نے یہ ہمارے سامنے رکھا",
    "Wretched is the settlement": "کیا بُرا ٹھکانا ہے",
    "Our Lord, whoever brought this upon us - increase for him double punishment in Fire": "اے ہمارے رب، جس نے ہمیں اس میں مبتلا کیا اس کا عذاب آگ میں دگنا کر دے",
    "They will say: What is wrong with us that we do not see men we used to count among the worst?": "وہ کہیں گے: ہمیں کیا ہو گیا کہ ہم ان لوگوں کو نہیں دیکھتے جنہیں ہم بُروں میں شمار کرتے تھے؟",
    "Did we take them in ridicule?": "کیا ہم نے ان کا مذاق اڑایا تھا؟",
    "Or have our eyes turned away from them?": "یا ہماری نظریں ان سے پھر گئی ہیں؟",
    "Indeed, that is truth - the quarreling of the people of Fire": "بے شک یہ سچ ہے - دوزخ والوں کا جھگڑا",
    // propheticMission
    "Say: I am only a warner": "کہو: میں صرف ڈرانے والا ہوں",
    "And there is no deity except Allah, the One, the Prevailing": "اور اللہ کے سوا کوئی معبود نہیں، ایک، غالب",
    "Lord of the heavens and the earth and what is between them": "آسمانوں اور زمین اور جو کچھ ان کے درمیان ہے سب کا رب",
    "The Mighty, the Perpetual Forgiver": "غالب، بار بار معاف کرنے والا",
    "Say: It is great news": "کہو: یہ ایک عظیم خبر ہے",
    "From which you are turning away": "جس سے تم منہ موڑ رہے ہو",
    "I had no knowledge of the exalted assembly when they disputed": "مجھے اعلیٰ مجلس کا کوئی علم نہیں تھا جب وہ بحث کر رہے تھے",
    "It is only revealed to me that I am a clear warner": "میری طرف صرف یہ وحی کی جاتی ہے کہ میں واضح ڈرانے والا ہوں",
    // iblisStory
    "When your Lord said to the angels: I am creating a human from clay": "جب تیرے رب نے فرشتوں سے کہا: میں مٹی سے انسان بنانے والا ہوں",
    "When I have proportioned him and breathed into him of My spirit": "جب میں اسے درست کر لوں اور اپنی روح اس میں پھونک دوں",
    "Then fall down to him prostrating": "تو اس کے لیے سجدے میں گر جاؤ",
    "So the angels prostrated, all of them entirely": "تو تمام فرشتے سجدے میں گر گئے، سب کے سب",
    "Except Iblis; he was arrogant and was among the disbelievers": "مگر ابلیس، اس نے تکبر کیا اور کافروں میں سے ہو گیا",
    "He said: O Iblis, what prevented you from prostrating to what I created with My hands?": "فرمایا: اے ابلیس، تجھے کس چیز نے اسے سجدہ کرنے سے روکا جسے میں نے اپنے ہاتھوں سے بنایا؟",
    "Were you arrogant or were you of the haughty?": "کیا تو نے تکبر کیا یا تو بلند مقام والوں میں سے تھا؟",
    "He said: I am better than him. You created me from fire and created him from clay": "اس نے کہا: میں اس سے بہتر ہوں۔ تو نے مجھے آگ سے بنایا اور اسے مٹی سے",
    "He said: Then get out of it, for indeed you are expelled": "فرمایا: نکل جا یہاں سے، بے شک تو مردود ہے",
    "And upon you is My curse until the Day of Judgment": "اور تجھ پر روزِ قیامت تک میری لعنت ہے",
    "He said: My Lord, then give me respite until the Day they are resurrected": "اس نے کہا: میرے رب، مجھے اٹھائے جانے کے دن تک مہلت دے",
    "He said: Indeed, you are of those reprieved": "فرمایا: بے شک تو مہلت پانے والوں میں سے ہے",
    "Until the Day of the Appointed Time": "مقررہ وقت کے دن تک",
    "He said: By Your might, I will surely mislead them all": "اس نے کہا: تیری عزت کی قسم، میں ان سب کو ضرور گمراہ کروں گا",
    "Except Your servants among them - the chosen ones": "مگر ان میں سے تیرے مخلص بندے",
    "He said: The truth [is My oath], and the truth I say": "فرمایا: حق ہے اور حق ہی کہتا ہوں",
    "I will surely fill Hell with you and those of them who follow you - all together": "میں جہنم کو تجھ سے اور ان میں سے تیری پیروی کرنے والوں سے ضرور بھر دوں گا - سب کو",
    // closingMessage
    "Say: I do not ask of you for it any payment": "کہو: میں تم سے اس پر کوئی اجر نہیں مانگتا",
    "And I am not of the pretentious": "اور میں بناوٹ کرنے والوں میں سے نہیں",
    "It is nothing but a reminder to the worlds": "یہ تمام جہانوں کے لیے ایک یاد دہانی کے سوا کچھ نہیں",
    "And you will surely know its truth after a time": "اور تم ایک مدت بعد اس کی خبر ضرور جان لو گے",
  },

  explanation: {
    // openingAndWarning
    "One of the mysterious letters (Huruf Muqatta'at) that begin certain surahs. Its exact meaning is known only to Allah.": "حروفِ مقطعات میں سے جو بعض سورتوں کی ابتدا میں آتے ہیں۔ ان کا حقیقی مطلب صرف اللہ کو معلوم ہے۔",
    "An oath by the Quran, described as containing dhikr - reminder, remembrance, and honor.": "قرآن کی قسم، جسے ذکر پر مشتمل بتایا گیا - یاد دہانی، ذکر اور عزت۔",
    "Disbelievers are in self-importance and opposition - their arrogance prevents acceptance of truth.": "کافر خود پسندی اور مخالفت میں ہیں - ان کا تکبر سچائی قبول کرنے سے روکتا ہے۔",
    "Warning from history - many nations destroyed for rejecting prophets. They cried out but too late.": "تاریخ سے تنبیہ - بہت سی قومیں انبیاء کو رد کرنے پر تباہ ہوئیں۔ انہوں نے فریاد کی مگر بہت دیر ہو چکی تھی۔",
    "The accusation of Quraysh against the Prophet - same accusation made against previous prophets.": "نبی ﷺ پر قریش کا الزام - وہی الزام جو پچھلے انبیاء پر لگایا گیا۔",
    "Disbelievers' shock at Tawheed - they couldn't accept the concept of One God.": "توحید پر کافروں کا صدمہ - وہ ایک خدا کا تصور قبول نہیں کر سکتے تھے۔",
    "Their sarcastic rejection of monotheism - finding unity of God strange while accepting multiple deities.": "توحید کا طنزیہ انکار - ایک خدا کو عجیب سمجھنا جبکہ متعدد معبود قبول۔",
    "Quraysh leaders urging each other to persist in polytheism - mockery and resistance to truth.": "قریش کے سردار ایک دوسرے کو شرک پر ثابت قدم رہنے کی ترغیب دے رہے - سچائی کا مذاق اور مزاحمت۔",
    "Claim that Tawheed was not in their forefathers' religion - preferring ancestral tradition over truth.": "دعویٰ کہ توحید ان کے باپ دادا کے دین میں نہیں تھی - سچائی پر آبائی روایت کو ترجیح۔",
    "Rhetorical question - they don't control prophethood or divine mercy. Allah chooses whom He wills.": "سوالِ انکاری - وہ نبوت یا الٰہی رحمت پر قابو نہیں رکھتے۔ اللہ جسے چاہے چنتا ہے۔",
    "Prophecy that the coalition against the Prophet would be defeated - fulfilled at Badr and beyond.": "پیشگوئی کہ نبی ﷺ کے خلاف اتحاد شکست کھائے گا - بدر اور اس کے بعد پوری ہوئی۔",
    // previousNations
    "Pattern of rejection - Nuh's people first in this list of deniers.": "انکار کا نمونہ - اس فہرست میں نوح کی قوم سب سے پہلے۔",
    "Pharaoh described as 'owner of stakes' - possibly referring to tent pegs of his vast army or impaling victims.": "فرعون کو 'میخوں والا' کہا گیا - ممکنہ طور پر اس کے بڑے لشکر کے خیمے یا لوگوں کو ٹانگنے کا حوالہ۔",
    "Continuation of destroyed nations - Thamud, Lut's people, Shu'ayb's people (Aykah).": "تباہ شدہ قوموں کا تسلسل - ثمود، لوط کی قوم، شعیب کی قوم (ایکہ)۔",
    "These destroyed nations were confederates against truth - just like Quraysh's coalition.": "یہ تباہ شدہ قومیں سچائی کے خلاف مخالفین تھیں - بالکل قریش کے اتحاد کی طرح۔",
    "Universal pattern - denial of messengers leads to deserved punishment.": "آفاقی نمونہ - رسولوں کا انکار مستحق سزا کی طرف لے جاتا ہے۔",
    "Warning that punishment can come suddenly - just one shout from the angel.": "تنبیہ کہ عذاب اچانک آ سکتا ہے - فرشتے کی صرف ایک چیخ۔",
    "Mocking demand for immediate punishment - they challenged Allah to punish them now.": "فوری سزا کا مذاق اڑاتا مطالبہ - انہوں نے اللہ کو ابھی سزا دینے کا چیلنج کیا۔",
    // dawudStory
    "Command to patience - Prophet consoled with stories of previous prophets' patience.": "صبر کا حکم - نبی ﷺ کو پچھلے انبیاء کے صبر کے قصوں سے تسلی۔",
    "Dawud introduced as Allah's servant with 'ayd' - strength in worship, body, and kingdom.": "داؤد کو اللہ کے بندے کے طور پر 'اید' (قوت) کے ساتھ متعارف کرایا - عبادت، جسم اور حکومت میں قوت۔",
    "Awwab - one who constantly returns to Allah in repentance. Key characteristic of Dawud.": "اوّاب - جو مسلسل توبہ کرتے ہوئے اللہ کی طرف لوٹتا ہے۔ داؤد کی کلیدی خصوصیت۔",
    "Mountains glorified Allah along with Dawud - miraculous praise at evening and sunrise.": "پہاڑ داؤد کے ساتھ اللہ کی تسبیح کرتے تھے - شام اور صبح معجزانہ تسبیح۔",
    "Times of Dawud's worship - evening and early morning. Mountains joined in praise.": "داؤد کی عبادت کے اوقات - شام اور صبح سویرے۔ پہاڑ تسبیح میں شامل۔",
    "Birds gathered to praise Allah with Dawud - all creation joining in worship.": "پرندے داؤد کے ساتھ اللہ کی تسبیح کے لیے جمع ہوتے - ساری مخلوق عبادت میں شامل۔",
    "Mountains and birds all joined Dawud in being 'awwab' - frequently turning to Allah.": "پہاڑ اور پرندے سب داؤد کے ساتھ 'اوّاب' بن گئے - اللہ کی طرف بار بار لوٹنے والے۔",
    "Allah established Dawud's rule firmly - strong governance and authority.": "اللہ نے داؤد کی حکومت مضبوطی سے قائم کی - مضبوط حکمرانی اور اختیار۔",
    "Two gifts: hikmah (wisdom) and fasl al-khitab (decisive judgment in speech/ruling).": "دو تحفے: حکمت اور فصل الخطاب (بات/فیصلے میں قطعیت)۔",
    "Two litigants climbed over Dawud's prayer chamber wall - sudden test of his judgment.": "دو فریق داؤد کے محراب کی دیوار سے چڑھ آئے - ان کے فیصلے کی اچانک آزمائش۔",
    "Dawud was startled by their sudden entry - unusual approach indicated test.": "داؤد ان کے اچانک داخلے سے گھبرا گیا - غیر معمولی طریقہ آزمائش کی طرف اشارہ تھا۔",
    "They presented their case - one claiming injustice from the other.": "انہوں نے اپنا معاملہ پیش کیا - ایک نے دوسرے سے ناانصافی کا دعویٰ کیا۔",
    "The parable: one has 99 sheep, the other has 1 - the rich one demanded the poor one's sheep.": "تمثیل: ایک کے پاس 99 دنبیاں، دوسرے کے پاس 1 - امیر نے غریب کی دنبی مانگی۔",
    "Stark inequality - 99 vs 1 - illustrating greed of the wealthy.": "واضح عدم مساوات - 99 بمقابلہ 1 - امیروں کی لالچ کی تصویر۔",
    "The demand - not satisfied with 99, wanting the poor man's only sheep.": "مطالبہ - 99 سے مطمئن نہیں، غریب کی اکلوتی دنبی چاہتے ہیں۔",
    "The rich one used eloquent speech to pressure the poor - power dynamics in disputes.": "امیر نے فصیح گفتگو سے غریب پر دباؤ ڈالا - تنازعات میں طاقت کی حرکیات۔",
    "Dawud's immediate judgment - declaring the demand as oppression.": "داؤد کا فوری فیصلہ - مطالبے کو ظلم قرار دینا۔",
    "Universal observation - business partners often wrong each other.": "آفاقی مشاہدہ - کاروباری شراکت دار اکثر ایک دوسرے پر ظلم کرتے ہیں۔",
    "Exception - believers who do good don't oppress, but they are few.": "استثناء - نیک ایمان والے ظلم نہیں کرتے، مگر وہ کم ہیں۔",
    "Dawud understood the case was a test - moment of self-realization.": "داؤد سمجھ گیا کہ معاملہ آزمائش تھی - خود شناسی کا لمحہ۔",
    "Dawud's immediate response - seeking forgiveness, prostrating, returning to Allah.": "داؤد کا فوری ردعمل - مغفرت طلب کرنا، سجدہ کرنا، اللہ کی طرف رجوع کرنا۔",
    "Allah's immediate forgiveness - sincere repentance is always accepted.": "اللہ کی فوری مغفرت - سچی توبہ ہمیشہ قبول ہوتی ہے۔",
    "Dawud's status with Allah - closeness (zulfa) and excellent final destination.": "اللہ کے نزدیک داؤد کا مقام - قربت (زلفیٰ) اور بہترین ٹھکانا۔",
    "Dawud appointed as khalifah - vicegerent and ruler with divine mandate.": "داؤد کو خلیفہ مقرر کیا - الٰہی حکم سے نائب اور حکمران۔",
    "Command to rule with justice and truth - core responsibility of leadership.": "عدل اور حق کے ساتھ حکومت کا حکم - قیادت کی بنیادی ذمہ داری۔",
    "Warning against following personal desires in judgment - leads to deviation.": "فیصلے میں ذاتی خواہشات کی پیروی سے تنبیہ - گمراہی کا سبب۔",
    "Consequence of deviation - severe punishment awaits those who abandon divine guidance.": "انحراف کا نتیجہ - الٰہی ہدایت چھوڑنے والوں کے لیے سخت سزا۔",
    "Root cause of deviation - forgetting accountability leads to following desires.": "انحراف کی بنیادی وجہ - احتساب بھولنا خواہشات کی پیروی کا سبب بنتا ہے۔",
    // sulaymanStory
    "Sulayman was a gift to Dawud - continuing the prophetic lineage.": "سلیمان داؤد کے لیے تحفہ تھا - نبوی سلسلے کا تسلسل۔",
    "Same praise as Dawud - 'ni'mal-'abd' (excellent servant) and 'awwab' (constantly returning to Allah).": "داؤد جیسی تعریف - 'نعم العبد' (بہترین بندہ) اور 'اوّاب' (مسلسل اللہ کی طرف لوٹنے والا)۔",
    "Fine horses were shown to Sulayman - standing on three legs, swift runners.": "سلیمان کے سامنے عمدہ گھوڑے پیش کیے گئے - تین ٹانگوں پر کھڑے، تیز دوڑنے والے۔",
    "Sulayman's realization - worldly good distracted him from remembering Allah.": "سلیمان کی خبرداری - دنیاوی بھلائی نے اسے اللہ کی یاد سے غافل کر دیا۔",
    "He was distracted until sunset - missing the time for worship.": "غروب آفتاب تک مشغول رہا - عبادت کا وقت نکل گیا۔",
    "Sulayman commanded the horses be brought back.": "سلیمان نے حکم دیا کہ گھوڑے واپس لاؤ۔",
    "Some say he stroked them lovingly; others say he sacrificed them to remove the distraction.": "بعض کہتے ہیں اس نے پیار سے ہاتھ پھیرا؛ دوسرے کہتے ہیں اس نے توجہ ہٹانے کے لیے قربان کیے۔",
    "Sulayman was also tested - even great prophets face trials.": "سلیمان کو بھی آزمایا گیا - عظیم انبیاء کو بھی آزمائشوں کا سامنا ہوتا ہے۔",
    "A body was placed on his throne - various interpretations of this trial.": "اس کے تخت پر ایک جسد رکھا گیا - اس آزمائش کی مختلف تعبیرات۔",
    "After the test, Sulayman returned to Allah - consistent pattern of prophetic repentance.": "آزمائش کے بعد سلیمان نے اللہ کی طرف رجوع کیا - نبوی توبہ کا مسلسل نمونہ۔",
    "Sulayman's prayer - seeking forgiveness first, then asking for unique kingdom.": "سلیمان کی دعا - پہلے مغفرت، پھر بے مثال سلطنت مانگی۔",
    "Request for unique, unparalleled kingdom - not from greed but divine purpose.": "بے مثال سلطنت کی درخواست - لالچ سے نہیں بلکہ الٰہی مقصد سے۔",
    "Acknowledging Allah as Al-Wahhab - the One who gives abundantly.": "اللہ کو الوہاب مان کر - وہ جو بے حد عطا کرتا ہے۔",
    "Wind controlled by Sulayman - traveled wherever he directed it.": "ہوا سلیمان کے تابع - جہاں اس نے چاہا وہاں چلی۔",
    "The wind was gentle (rukhaa'), not destructive - controlled power.": "ہوا نرم (رخاء) تھی، تباہ کن نہیں - قابو میں طاقت۔",
    "Jinn subjected to Sulayman - some building, some diving for pearls.": "جنات سلیمان کے تابع - کچھ تعمیر کرتے، کچھ موتیوں کے لیے غوطہ لگاتے۔",
    "Some jinn were restrained in chains - rebellious ones kept under control.": "بعض جنات زنجیروں میں جکڑے - سرکش قابو میں رکھے گئے۔",
    "Complete freedom given to Sulayman - give or withhold from his kingdom freely.": "سلیمان کو مکمل آزادی دی گئی - اپنی سلطنت سے دینا یا روکنا آزاد ہے۔",
    "Same honor as Dawud - closeness to Allah and excellent final destination.": "داؤد جیسا اعزاز - اللہ سے قربت اور بہترین ٹھکانا۔",
    // ayyubStory
    "Ayyub introduced as Allah's servant - model of patience in suffering.": "ایوب کو اللہ کے بندے کے طور پر متعارف - مصائب میں صبر کا نمونہ۔",
    "Ayyub's call to Allah - attributing his affliction to Satan's touch, maintaining adab with Allah.": "ایوب کی اللہ سے فریاد - اپنی مصیبت شیطان کی طرف منسوب، اللہ کے ساتھ ادب برقرار۔",
    "Allah's command to Ayyub - strike the ground to release healing water.": "اللہ کا ایوب کو حکم - زمین پر پاؤں مارو تاکہ شفا کا پانی نکلے۔",
    "Miraculous spring emerged - cool water for washing (healing) and drinking.": "معجزانہ چشمہ نکلا - نہانے (شفا) اور پینے کا ٹھنڈا پانی۔",
    "Allah restored his family and doubled it - reward for patience.": "اللہ نے اس کا گھرانا بحال کیا اور دگنا کر دیا - صبر کا انعام۔",
    "Ayyub's restoration was divine mercy and lesson for people of intellect.": "ایوب کی بحالی الٰہی رحمت اور عقلمندوں کے لیے سبق تھی۔",
    "Solution for Ayyub's oath - he had sworn to strike his wife, so Allah provided easy fulfillment.": "ایوب کی قسم کا حل - اس نے بیوی کو مارنے کی قسم کھائی تھی، اللہ نے آسان طریقہ مہیا کیا۔",
    "Merciful solution - symbolic strike with grass bundle to fulfill oath without harm.": "رحمت والا حل - قسم پوری کرنے کے لیے گھاس کے گچھے سے علامتی ضرب بغیر نقصان۔",
    "Allah's testimony about Ayyub - found to be truly patient through all trials.": "ایوب کے بارے میں اللہ کی گواہی - تمام آزمائشوں میں حقیقی صبر کرنے والا پایا۔",
    "Same praise given to Ayyub - excellent servant and constantly returning to Allah.": "ایوب کو بھی وہی تعریف - بہترین بندہ اور مسلسل اللہ کی طرف لوٹنے والا۔",
    // otherProphets
    "Three generations of prophets mentioned together - grandfather, father, son.": "تین نسلوں کے انبیاء ایک ساتھ - دادا، باپ، بیٹا۔",
    "Praised for 'ayd' (strength in worship/action) and 'absar' (insight/vision).": "'اید' (عبادت/عمل میں قوت) اور 'ابصار' (بصیرت/نظر) کے لیے تعریف۔",
    "They were distinguished by constant remembrance of the Hereafter.": "وہ آخرت کی مسلسل یاد سے ممتاز تھے۔",
    "Highest praise - selected (mustafa) and best (akhyar) in Allah's sight.": "بلند ترین تعریف - اللہ کی نظر میں چنیدہ (مصطفیٰ) اور بہترین (اخیار)۔",
    "Three more prophets mentioned - Ismail, Al-Yasa (Elisha), and Dhul-Kifl.": "تین مزید انبیاء کا ذکر - اسماعیل، الیسع اور ذوالکفل۔",
    "All these prophets are among the best of humanity.": "یہ سب انبیاء انسانیت کے بہترین لوگوں میں سے ہیں۔",
    // paradise
    "Transition - the previous stories serve as dhikr (reminder) for believers.": "تبدیلی - پچھلے قصے مومنوں کے لیے ذکر (یاد دہانی) کا کام کرتے ہیں۔",
    "Promise for the muttaqeen (God-conscious) - excellent final destination.": "متقیوں (خدا ترس) کے لیے وعدہ - بہترین ٹھکانا۔",
    "Gardens of Eden with gates already open - welcoming the righteous.": "عدن کے باغات دروازے پہلے سے کھلے - نیکوکاروں کا استقبال۔",
    "Comfortable reclining, abundant fruits and drinks at their call.": "آرام سے تکیہ لگائے، بلانے پر بے شمار پھل اور مشروبات۔",
    "Companions with modest gazes, all of same age - perfect companions.": "نگاہیں جھکائے ہم عمر ساتھی - کامل رفیقائیں۔",
    "Confirmation - these rewards are promised for the Day of Judgment.": "تصدیق - یہ انعامات یومِ حساب کے لیے وعدہ ہیں۔",
    "Allah's provision in Paradise - never-ending, inexhaustible.": "جنت میں اللہ کا رزق - نہ ختم ہونے والا، لا محدود۔",
    // hellfire
    "Contrast - those who transgress will have the worst destination.": "تضاد - سرکشی کرنے والوں کا بدترین ٹھکانا ہوگا۔",
    "Jahannam - they will enter and experience its burning.": "جہنم - وہ اس میں داخل ہوں گے اور اس کی جلن محسوس کریں گے۔",
    "Terrible bed/resting place - opposite of the comfort in Paradise.": "خوفناک بستر/آرام گاہ - جنت کے آرام کا الٹ۔",
    "Two punishments: hameem (boiling water) and ghassaq (pus or freezing cold).": "دو عذاب: حمیم (کھولتا پانی) اور غساق (پیپ یا شدید سردی)۔",
    "Multiple paired punishments - various types of torment.": "متعدد جوڑے دار عذاب - مختلف قسم کے عذاب۔",
    "Groups rushing into Hell together - leaders and followers.": "جماعتیں مل کر جہنم میں گھسی آ رہی ہیں - قائدین اور پیروکار۔",
    "No welcome - instead of hospitality, they receive curse and torment.": "خوش آمدید نہیں - مہمان نوازی کی بجائے لعنت اور عذاب۔",
    "Confirmation of their entry into the Fire.": "ان کے آگ میں داخلے کی تصدیق۔",
    "Followers blame leaders - mutual accusation in Hell.": "پیروکار قائدین کو ذمہ دار ٹھہراتے ہیں - جہنم میں باہمی الزام تراشی۔",
    "Followers accuse leaders of leading them to this fate.": "پیروکار قائدین پر الزام لگاتے ہیں کہ انہوں نے اس انجام تک پہنچایا۔",
    "Terrible final abode - permanent misery.": "خوفناک حتمی ٹھکانا - ابدی تکلیف۔",
    "They pray against those who misled them - wanting double punishment for leaders.": "وہ گمراہ کرنے والوں کے خلاف دعا کرتے ہیں - قائدین کے لیے دگنے عذاب کی خواہش۔",
    "Disbelievers wonder where the believers are - whom they mocked as evil.": "کافر حیران ہیں کہ مومن کہاں ہیں - جنہیں وہ بُرا سمجھتے اور مذاق اڑاتے تھے۔",
    "Realization that they mocked the righteous - now the righteous are not in Hell.": "احساس ہوا کہ انہوں نے نیکوکاروں کا مذاق اڑایا - اب نیکوکار جہنم میں نہیں ہیں۔",
    "Wondering if they simply can't see the believers - ironic spiritual blindness.": "سوچتے ہیں شاید مومنوں کو دیکھ نہیں سکتے - ستم ظریف روحانی اندھاپن۔",
    "Allah confirms this mutual accusation in Hell is reality - they will argue forever.": "اللہ تصدیق کرتا ہے کہ جہنم میں یہ باہمی الزام تراشی حقیقت ہے - وہ ہمیشہ جھگڑتے رہیں گے۔",
    // propheticMission
    "Prophet's role defined - a warner, not controller of people's choices.": "نبی ﷺ کا کردار متعین - ڈرانے والا، نہ کہ لوگوں کے فیصلوں کا مالک۔",
    "Core message - Tawheed. Allah is One (Wahid) and Dominant (Qahhar).": "بنیادی پیغام - توحید۔ اللہ ایک (واحد) اور غالب (قہار) ہے۔",
    "Allah's sovereignty over all creation - heavens, earth, and everything between.": "تمام مخلوقات پر اللہ کی حاکمیت - آسمان، زمین اور جو کچھ ان کے درمیان ہے۔",
    "Two divine names: 'Azeez (Mighty/Powerful) and Ghaffar (Repeatedly Forgiving).": "دو الٰہی نام: عزیز (غالب/طاقتور) اور غفار (بار بار معاف کرنے والا)۔",
    "The Quran/message is tremendous news - not to be taken lightly.": "قرآن/پیغام عظیم خبر ہے - ہلکا نہیں لینا۔",
    "Despite its greatness, they turn away heedlessly.": "اس کی عظمت کے باوجود، وہ بے خبری سے منہ موڑ لیتے ہیں۔",
    "Prophet had no prior knowledge of angelic discussions - proof of revelation.": "نبی ﷺ کو فرشتوں کی بحث کا پہلے سے علم نہیں تھا - وحی کا ثبوت۔",
    "The Prophet's role is clear warning - not claim to divine knowledge on his own.": "نبی ﷺ کا کردار واضح تنبیہ ہے - اپنی طرف سے الٰہی علم کا دعویٰ نہیں۔",
    // iblisStory
    "Allah announces Adam's creation from clay - setting the scene for the test.": "اللہ مٹی سے آدم کی تخلیق کا اعلان کرتا ہے - آزمائش کا منظر تیار۔",
    "Two stages: physical formation and divine spirit - human dignity from Allah's breath.": "دو مراحل: جسمانی تشکیل اور الٰہی روح - اللہ کی روح سے انسانی وقار۔",
    "Command to prostrate to Adam - gesture of honor, not worship.": "آدم کو سجدہ کرنے کا حکم - عزت کا اشارہ، عبادت نہیں۔",
    "All angels obeyed without exception - complete submission to Allah's command.": "تمام فرشتوں نے بلا استثناء اطاعت کی - اللہ کے حکم کی مکمل تابعداری۔",
    "Iblis refused due to arrogance (istikbar) - making him a disbeliever.": "ابلیس نے تکبر (استکبار) کی وجہ سے انکار کیا - جس سے وہ کافر بن گیا۔",
    "Allah questions Iblis - Adam was created by Allah's own hands, deserving honor.": "اللہ ابلیس سے سوال کرتا ہے - آدم اللہ کے اپنے ہاتھوں سے بنایا گیا، عزت کا مستحق۔",
    "Question exposing Iblis's arrogance - no valid excuse for disobedience.": "ابلیس کے تکبر کو بے نقاب کرنے والا سوال - نافرمانی کا کوئی جائز عذر نہیں۔",
    "Iblis's argument - fire is superior to clay. Flawed reasoning based on material origin.": "ابلیس کی دلیل - آگ مٹی سے بہتر ہے۔ مادی اصل پر مبنی غلط استدلال۔",
    "Iblis expelled from Paradise - rajeem (stoned, accursed, expelled).": "ابلیس جنت سے نکالا گیا - رجیم (ملعون، مردود، نکالا ہوا)۔",
    "Perpetual curse on Iblis - lasting until the Day of Judgment.": "ابلیس پر ابدی لعنت - قیامت کے دن تک۔",
    "Iblis asks for time - to mislead humans until resurrection.": "ابلیس وقت مانگتا ہے - قیامت تک انسانوں کو گمراہ کرنے کے لیے۔",
    "Allah grants respite - part of the test for humanity.": "اللہ مہلت دیتا ہے - انسانیت کی آزمائش کا حصہ۔",
    "Respite until a known time - Allah's wisdom in the duration.": "معلوم وقت تک مہلت - مدت میں اللہ کی حکمت۔",
    "Iblis swears by Allah's might to mislead all humans - vow of enmity.": "ابلیس اللہ کی عزت کی قسم کھا کر تمام انسانوں کو گمراہ کرنے کا عہد - دشمنی کی قسم۔",
    "Iblis admits inability to mislead sincere servants - Allah's protection for the devoted.": "ابلیس مخلص بندوں کو گمراہ کرنے سے عاجزی کا اعتراف - وقف شدگان کے لیے اللہ کی حفاظت۔",
    "Allah swears by the Truth (Himself) - about to declare truth.": "اللہ حق (خود) کی قسم کھاتا ہے - سچائی بیان کرنے والا ہے۔",
    "Allah's decree - Hell will be filled with Iblis and his followers from humans.": "اللہ کا فیصلہ - جہنم ابلیس اور اس کے انسانی پیروکاروں سے بھر دی جائے گی۔",
    // closingMessage
    "Prophet seeks no worldly compensation - proof of sincerity.": "نبی ﷺ دنیاوی اجر نہیں مانگتے - اخلاص کا ثبوت۔",
    "No pretense or false claims - authentic message without affectation.": "نہ دکھاوا نہ جھوٹے دعوے - بغیر بناوٹ حقیقی پیغام۔",
    "The Quran is dhikr (reminder) for all of creation - universal message.": "قرآن تمام مخلوقات کے لیے ذکر (یاد دہانی) ہے - آفاقی پیغام۔",
    "Final warning - they will know the truth later, whether in this life or the next.": "آخری تنبیہ - وہ سچائی بعد میں جان لیں گے، چاہے اس زندگی میں یا اگلی میں۔",
  }
};

// Apply translations
const filePath = path.resolve('src/data/treebank/ontology/038.js');
let content = fs.readFileSync(filePath, 'utf8');

for (const [en, ur] of Object.entries(TRANSLATIONS.meaning)) {
  const escaped = en.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  content = content.replace(new RegExp(`meaning: "${escaped}"`, 'g'), `meaning: { en: "${en}", ur: "${ur}" }`);
}

for (const [en, ur] of Object.entries(TRANSLATIONS.explanation)) {
  const escaped = en.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  content = content.replace(new RegExp(`explanation: "${escaped}"`, 'g'), `explanation: { en: "${en}", ur: "${ur}" }`);
}

fs.writeFileSync(filePath, content, 'utf8');

// Count remaining
const remMeaning = (content.match(/meaning: "[^{]/g) || []).length;
const remExpl = (content.match(/explanation: "[^{]/g) || []).length;
console.log(`038.js transformed. Remaining: meaning=${remMeaning}, explanation=${remExpl}`);
