#!/usr/bin/env node
/**
 * Script to convert plain string fields in ontology files to bilingual {en, ur} objects.
 * This handles the mechanical conversion, and Urdu translations are provided inline.
 */

import fs from 'fs';
import path from 'path';

// We'll read the file, parse the JS object, transform text fields, and write back.
// Since these are JS files with exports, we'll use dynamic import.

const URDU_TRANSLATIONS_026 = {
  // musaStoryPart3
  "Did we not raise you among us as a child?": "کیا ہم نے تمہیں اپنے میں بچپن سے نہیں پالا؟",
  "Pharaoh's reminder of upbringing": "فرعون کی پرورش کی یاد دہانی",
  "And you remained among us years of your life": "اور تم ہمارے میں اپنی عمر کے کئی سال رہے",
  "Years spent in palace": "محل میں گزارے ہوئے سال",
  "And you did your deed which you did": "اور تم نے وہ کام کیا جو تم نے کیا",
  "Reference to killing Egyptian": "مصری کے قتل کا حوالہ",
  "And you were ungrateful": "اور تم ناشکروں میں سے تھے",
  "Pharaoh's accusation": "فرعون کا الزام",
  "I did it then when I was astray": "میں نے وہ کام اس وقت کیا جب میں بے خبروں میں سے تھا",
  "Musa's acknowledgment before guidance": "ہدایت سے پہلے موسیٰ کا اعتراف",
  "So I fled from you when I feared you": "تو میں تم سے بھاگ گیا جب مجھے تم سے ڈر لگا",
  "Flight to Madyan": "مدین کی طرف فرار",
  "Then my Lord granted me wisdom": "پھر میرے رب نے مجھے حکمت عطا فرمائی",
  "Divine gift of prophethood": "نبوت کا الٰہی عطیہ",
  "And made me one of the messengers": "اور مجھے رسولوں میں سے بنایا",
  "Prophet status": "نبوت کا مقام",

  // musaStoryPart4
  "And is this a favor you remind me of - that you enslaved Israel?": "اور یہ کیا احسان ہے جو تو مجھ پر جتاتا ہے کہ تو نے بنی اسرائیل کو غلام بنایا؟",
  "Musa exposes the irony": "موسیٰ نے ستم ظریفی کو بے نقاب کیا",
  "Pharaoh said: And what is the Lord of the worlds?": "فرعون نے کہا: رب العالمین کیا ہے؟",
  "Pharaoh's challenge": "فرعون کا چیلنج",
  "He said: Lord of heavens and earth and what is between": "اس نے کہا: آسمانوں اور زمین اور جو کچھ ان کے درمیان ہے ان کا رب",
  "Musa's description of Allah": "موسیٰ کی اللہ کی توصیف",
  "If you are certain": "اگر تم یقین رکھتے ہو",
  "Challenge to reflect": "غور و فکر کی دعوت",
  "He said to those around: Do you not hear?": "اس نے اپنے اردگرد والوں سے کہا: سنتے نہیں؟",
  "Pharaoh mocks Musa": "فرعون نے موسیٰ کا مذاق اڑایا",
  "He said: Your Lord and Lord of your forefathers": "اس نے کہا: تمہارا اور تمہارے باپ دادا کا رب",
  "Musa expands definition": "موسیٰ نے تعریف کو وسیع کیا",
  "He said: Your messenger sent to you is mad": "اس نے کہا: تمہارا یہ رسول جو تم کی طرف بھیجا گیا پاگل ہے",
  "Pharaoh's insult": "فرعون کی توہین",
  "He said: Lord of East and West and what is between": "اس نے کہا: مشرق و مغرب اور جو کچھ ان کے درمیان ہے ان کا رب",
  "Musa's third description": "موسیٰ کی تیسری توصیف",
  "If you use reason": "اگر تم عقل رکھتے ہو",
  "Appeal to intellect": "عقل سے اپیل",

  // musaStoryPart5
  "He said: If you take a god other than me, I will imprison you": "اس نے کہا: اگر تو نے میرے سوا کوئی معبود بنایا تو میں تجھے قیدیوں میں کر دوں گا",
  "Pharaoh's threat": "فرعون کی دھمکی",
  "He said: Even if I brought you clear proof?": "اس نے کہا: اگرچہ میں تمہارے پاس واضح چیز لاؤں؟",
  "Musa offers evidence": "موسیٰ نے ثبوت پیش کرنے کی پیشکش کی",
  "So he threw his staff and it became a clear serpent": "تو اس نے اپنا عصا پھینکا اور وہ ایک واضح اژدھا بن گیا",
  "First miracle": "پہلا معجزہ",
  "He drew out his hand and it was white for beholders": "اور اس نے اپنا ہاتھ نکالا تو وہ دیکھنے والوں کے لیے چمکدار سفید تھا",
  "Second miracle": "دوسرا معجزہ",
  "He said to the eminent ones: This is a learned magician": "اس نے سرداروں سے کہا: یہ تو ایک ماہر جادوگر ہے",
  "Pharaoh's dismissal as magic": "فرعون کا جادو کہہ کر مسترد کرنا",
  "He wants to drive you out of your land by his magic": "یہ اپنے جادو سے تمہیں تمہاری سرزمین سے نکالنا چاہتا ہے",
  "Political accusation": "سیاسی الزام",
  "They said: Postpone him and his brother and send gatherers to the cities": "انہوں نے کہا: اسے اور اس کے بھائی کو مہلت دو اور شہروں میں جمع کرنے والے بھیجو",
  "Plan to summon magicians": "جادوگروں کو بلانے کا منصوبہ",
  "To bring every skilled magician": "ہر ماہر جادوگر کو لائیں",
  "Gathering magicians": "جادوگروں کا اجتماع",

  // musaStoryPart6
  "So the magicians were assembled for appointment of a known day": "تو جادوگر ایک مقررہ دن کے وقت جمع کیے گئے",
  "Public contest arranged": "عوامی مقابلے کا اہتمام",
  "And it was said to people: Will you assemble?": "اور لوگوں سے کہا گیا: کیا تم جمع ہوتے ہو؟",
  "Public gathering called": "عوامی اجتماع کا اعلان",
  "Perhaps we will follow the magicians if they prevail": "شاید ہم جادوگروں کی پیروی کریں اگر وہ غالب آئیں",
  "Stakes of the contest": "مقابلے کا داؤ",
  "They said to Pharaoh: Is there a reward if we prevail?": "انہوں نے فرعون سے کہا: کیا ہمارے لیے اجر ہے اگر ہم غالب آئیں؟",
  "Magicians bargain": "جادوگروں کا سودا",
  "He said: Yes, and you will be among those near me": "اس نے کہا: ہاں اور تم میرے مقربین میں سے ہو جاؤ گے",
  "Promise of status": "مقام کا وعدہ",
  "Musa said: Throw what you will throw": "موسیٰ نے کہا: جو تمہیں ڈالنا ہے ڈالو",
  "Musa's confidence": "موسیٰ کا اعتماد",
  "So they threw their ropes and staffs": "تو انہوں نے اپنی رسیاں اور لاٹھیاں پھینکیں",
  "Magicians' trick": "جادوگروں کی چال",
  "And said: By Pharaoh's might, we will prevail": "اور کہا: فرعون کی عزت کی قسم، ہم ہی غالب آئیں گے",
  "Swearing by Pharaoh": "فرعون کی قسم کھانا",
  "Then Musa threw his staff and it swallowed what they faked": "پھر موسیٰ نے اپنا عصا پھینکا تو وہ ان کے بناوٹی کاموں کو نگلنے لگا",
  "Truth devours falsehood": "حق نے باطل کو نگل لیا",

  // musaStoryPart7
  "So the magicians fell in prostration": "تو جادوگر سجدے میں گر گئے",
  "Immediate submission to truth": "حق کے سامنے فوری تسلیم",
  "They said: We believe in the Lord of the worlds": "انہوں نے کہا: ہم رب العالمین پر ایمان لائے",
  "Declaration of faith": "ایمان کا اعلان",
  "Lord of Musa and Harun": "موسیٰ اور ہارون کا رب",
  "Specifying their belief": "ایمان کی تخصیص",
  "He said: You believed before I gave permission": "اس نے کہا: تم نے میری اجازت سے پہلے ایمان لے آئے؟",
  "Pharaoh's outrage": "فرعون کا غصہ",
  "He is your chief who taught you magic": "یہ تمہارا بڑا ہے جس نے تمہیں جادو سکھایا",
  "Pharaoh's conspiracy theory": "فرعون کی سازشی سوچ",
  "So you will know": "تو تم جلد جان لو گے",
  "Pharaoh's ominous warning": "فرعون کی شومِ تنبیہ",
  "I will cut your hands and feet on opposite sides": "میں تمہارے ہاتھ اور پاؤں الٹی طرف سے کاٹوں گا",
  "Torture threat": "تشدد کی دھمکی",
  "And I will crucify you all": "اور تم سب کو سولی پر چڑھاؤں گا",
  "Death threat": "موت کی دھمکی",

  // musaStoryPart8
  "They said: No harm": "انہوں نے کہا: کوئی نقصان نہیں",
  "Fearless response": "بے خوف جواب",
  "Indeed to our Lord we will return": "بے شک ہم اپنے رب کی طرف لوٹنے والے ہیں",
  "Trust in afterlife": "آخرت پر بھروسہ",
  "We hope our Lord forgives our sins": "ہم امید رکھتے ہیں کہ ہمارا رب ہماری خطائیں معاف فرمائے",
  "Hope for forgiveness": "مغفرت کی امید",
  "Since we are the first believers": "کیونکہ ہم سب سے پہلے ایمان لانے والے ہیں",
  "Pride in being first to believe": "سب سے پہلے ایمان لانے کا فخر",

  // musaStoryPart9
  "We revealed to Musa: Travel by night with My servants": "ہم نے موسیٰ کو وحی کی کہ میرے بندوں کو رات میں لے جاؤ",
  "Command to leave Egypt": "مصر چھوڑنے کا حکم",
  "You will be pursued": "تمہارا پیچھا کیا جائے گا",
  "Warning of pursuit": "تعاقب کی تنبیہ",
  "So Pharaoh sent gatherers to the cities": "تو فرعون نے شہروں میں جمع کرنے والے بھیجے",
  "Pharaoh mobilizes army": "فرعون نے لشکر تیار کیا",
  "Indeed these are a small band": "بے شک یہ ایک چھوٹا سا گروہ ہے",
  "Pharaoh's dismissal": "فرعون کی حقارت",
  "And they have enraged us": "اور انہوں نے ہمیں غصہ دلایا ہے",
  "Pharaoh's anger": "فرعون کا غصہ",
  "And we are all cautious": "اور ہم سب چوکنے ہیں",
  "Military preparation": "فوجی تیاری",
  "So We removed them from gardens and springs": "تو ہم نے انہیں باغات اور چشموں سے نکال دیا",
  "Egypt's loss of Pharaoh's people": "فرعون کے لوگوں کا مصر سے محرومی",
  "And treasures and noble position": "اور خزانوں اور عزت والے مقام سے",
  "Worldly loss": "دنیاوی نقصان",
  "Thus, and We made Israel inherit it": "اسی طرح اور ہم نے بنی اسرائیل کو اس کا وارث بنایا",
  "Transfer of inheritance": "وراثت کی منتقلی",

  // musaStoryPart10
  "So they pursued them at sunrise": "تو انہوں نے سورج نکلتے وقت ان کا پیچھا کیا",
  "Chase at dawn": "صبح کا تعاقب",
  "When the two groups saw each other": "جب دونوں گروہوں نے ایک دوسرے کو دیکھا",
  "Confrontation moment": "مقابلے کا لمحہ",
  "Companions of Musa said: We will be overtaken": "موسیٰ کے ساتھیوں نے کہا: ہم پکڑے جائیں گے",
  "Moment of fear": "خوف کا لمحہ",
  "He said: No! My Lord is with me, He will guide me": "اس نے کہا: ہرگز نہیں! میرا رب میرے ساتھ ہے، وہ مجھے راستہ دکھائے گا",
  "Musa's absolute trust": "موسیٰ کا مکمل توکل",
  "We revealed to Musa: Strike the sea with your staff": "ہم نے موسیٰ کو وحی کی: اپنا عصا سمندر پر مارو",
  "Command to part sea": "سمندر پھاڑنے کا حکم",
  "So it parted, each part like a great mountain": "تو وہ پھٹ گیا، ہر حصہ بڑے پہاڑ کی طرح",
  "Sea splits into towering walls": "سمندر اونچی دیواروں میں تقسیم ہوا",
  "And We brought near the others there": "اور ہم نے وہاں دوسروں کو قریب لایا",
  "Pharaoh's army approaches": "فرعون کا لشکر نزدیک آیا",
  "And We saved Musa and all those with him": "اور ہم نے موسیٰ اور ان کے ساتھیوں سب کو بچا لیا",
  "Believers saved": "مومنوں کو بچایا گیا",
  "Then We drowned the others": "پھر ہم نے باقیوں کو غرق کر دیا",
  "Pharaoh's army destroyed": "فرعون کا لشکر تباہ ہوا",
  "In that is a sign, but most were not believers": "اس میں ایک نشانی ہے لیکن اکثر ایمان لانے والے نہیں تھے",
  "Lesson and reality": "سبق اور حقیقت",

  // ibrahimStory
  "Recite to them the story of Ibrahim": "ان پر ابراہیم کا قصہ پڑھو",
  "Command to narrate": "بیان کرنے کا حکم",
  "When he said to his father and people: What do you worship?": "جب اس نے اپنے باپ اور قوم سے کہا: تم کیا پوجتے ہو؟",
  "Opening challenge": "ابتدائی چیلنج",
  "They said: We worship idols and remain devoted to them": "انہوں نے کہا: ہم بتوں کی پوجا کرتے ہیں اور ان کے عبادت گزار رہتے ہیں",
  "Confession of idolatry": "بت پرستی کا اعتراف",
  "He said: Do they hear you when you call?": "اس نے کہا: کیا وہ تمہاری سنتے ہیں جب تم پکارتے ہو؟",
  "First logical question": "پہلا عقلی سوال",
  "Or do they benefit or harm you?": "یا تمہیں نفع یا نقصان پہنچاتے ہیں؟",
  "Second logical question": "دوسرا عقلی سوال",
  "They said: We found our fathers doing so": "انہوں نے کہا: ہم نے اپنے باپ دادا کو ایسا کرتے پایا",
  "Appeal to tradition": "روایت سے استدلال",
  "He said: Have you considered what you worship?": "اس نے کہا: کیا تم نے غور کیا جن کی تم عبادت کرتے ہو؟",
  "Ibrahim challenges tradition": "ابراہیم نے روایت کو چیلنج کیا",
  "You and your ancient forefathers?": "تم اور تمہارے پچھلے باپ دادا؟",
  "Questioning generations": "نسلوں پر سوال",
  "They are enemies to me, except the Lord of the worlds": "یہ سب میرے دشمن ہیں سوائے رب العالمین کے",
  "Rejection of false gods": "جھوٹے معبودوں کی تردید",

  // ibrahimPraise
  "Who created me, and He guides me": "جس نے مجھے پیدا کیا اور وہی مجھے راستہ دکھاتا ہے",
  "Creator and Guide": "خالق اور ہادی",
  "Who feeds me and gives me drink": "جو مجھے کھلاتا اور پلاتا ہے",
  "Provider of sustenance": "رزق دینے والا",
  "When I am ill, He heals me": "اور جب میں بیمار ہوتا ہوں تو وہ مجھے شفا دیتا ہے",
  "Healer - illness attributed to self, healing to Allah": "شفا دینے والا - بیماری اپنی طرف اور شفا اللہ کی طرف منسوب کی",
  "Who will cause me to die and then bring me back": "جو مجھے موت دے گا پھر مجھے زندہ کرے گا",
  "Lord of death and resurrection": "موت اور حیاتِ نو کا رب",
  "Who I hope will forgive my sins on Judgment Day": "جس سے میں امید رکھتا ہوں کہ وہ قیامت کے دن میری خطائیں معاف فرمائے گا",
  "Forgiver on Day of Judgment": "قیامت کے دن معاف فرمانے والا",

  // ibrahimDua
  "My Lord, grant me wisdom and join me with the righteous": "اے میرے رب مجھے حکمت عطا فرما اور مجھے صالحین میں شامل کر",
  "Prayer for wisdom and company": "حکمت اور نیک صحبت کی دعا",
  "And grant me a truthful mention among later generations": "اور بعد والوں میں میری سچی ذکر باقی رکھ",
  "Prayer for lasting good reputation": "پائیدار نیک نامی کی دعا",
  "Make me among the inheritors of Paradise": "مجھے جنت النعیم کے وارثوں میں شامل فرما",
  "Prayer for Paradise": "جنت کی دعا",
  "And forgive my father, he was among the astray": "اور میرے باپ کو معاف فرما، وہ گمراہوں میں سے تھا",
  "Prayer for father - before prohibition": "والد کے لیے دعا - ممانعت سے پہلے",
  "Do not disgrace me on the Day they are resurrected": "مجھے اس دن رسوا نہ کر جب سب اٹھائے جائیں گے",
  "Prayer for dignity on Judgment Day": "قیامت کے دن عزت کی دعا",
  "Day when neither wealth nor children will benefit": "وہ دن جب نہ مال کام آئے گا نہ اولاد",
  "Description of Judgment Day": "قیامت کے دن کی تصویر",
  "Except one who comes to Allah with a sound heart": "سوائے اس کے جو اللہ کے پاس صاف دل لے کر آئے",
  "The only thing that benefits - pure heart": "واحد فائدہ مند چیز - قلبِ سلیم",

  // paradiseAndHell
  "Paradise will be brought near the God-fearing": "جنت پرہیزگاروں کے قریب لائی جائے گی",
  "Paradise approaches the pious": "جنت متقین کے قریب آئے گی",
  "Hellfire will be displayed for the deviators": "جہنم گمراہوں کے سامنے ظاہر کی جائے گی",
  "Hell exposed to sinners": "جہنم گناہگاروں کے سامنے کھولی جائے گی",
  "They will be asked: Where are those you worshipped?": "ان سے پوچھا جائے گا: کہاں ہیں وہ جن کی تم عبادت کرتے تھے؟",
  "Question about false gods": "جھوٹے معبودوں کے بارے میں سوال",
  "Besides Allah? Can they help you or themselves?": "اللہ کے سوا؟ کیا وہ تمہاری یا اپنی مدد کر سکتے ہیں؟",
  "Helplessness of idols": "بتوں کی بے بسی",
  "They will be thrown into it, they and the deviators": "وہ اس میں گرائے جائیں گے، وہ اور گمراہ",
  "Idols and worshippers together in Hell": "بت اور پوجنے والے سب جہنم میں",
  "And the soldiers of Iblis, all of them": "اور ابلیس کے تمام لشکر",
  "Shaytan's army also punished": "شیطان کا لشکر بھی سزا یافتہ",

  // hellDialogue
  "They will say while disputing therein": "جب وہ اس میں جھگڑتے ہوئے کہیں گے",
  "Arguments in Hell": "جہنم میں بحث و تکرار",
  "By Allah, we were in clear error": "اللہ کی قسم ہم کھلی گمراہی میں تھے",
  "Confession too late": "بہت دیر سے اعتراف",
  "When we equated you with Lord of the worlds": "جب ہم تمہیں رب العالمین کے برابر ٹھہراتے تھے",
  "Sin of equating idols with Allah": "بتوں کو اللہ کے برابر ٹھہرانے کا گناہ",
  "Only the criminals led us astray": "ہمیں صرف مجرموں نے گمراہ کیا",
  "Blaming their leaders": "اپنے سرداروں پر الزام",
  "So we have no intercessors": "تو ہمارا کوئی سفارشی نہیں",
  "No one to intercede": "کوئی شفاعت کرنے والا نہیں",
  "Nor a close friend": "اور نہ کوئی قریبی دوست",
  "No true friends": "کوئی سچا دوست نہیں",
  "If only we could return and be believers": "کاش ہم واپس جائیں اور ایمان لانے والوں میں سے ہو جائیں",
  "Futile wish for return": "واپسی کی بے سود آرزو",

  // nuhStory
  "The people of Nuh denied the messengers": "قومِ نوح نے رسولوں کو جھٹلایا",
  "Denial of all messengers by denying one": "ایک کو جھٹلانے سے سب رسولوں کی تکذیب",
  "When their brother Nuh said: Will you not fear Allah?": "جب ان کے بھائی نوح نے کہا: کیا تم اللہ سے نہیں ڈرتے؟",
  "Nuh from among them": "نوح ان ہی میں سے تھے",
  "I am a trustworthy messenger to you": "میں تمہارے لیے ایک امانتدار رسول ہوں",
  "Trustworthiness claim": "امانت داری کا دعویٰ",
  "So fear Allah and obey me": "تو اللہ سے ڈرو اور میری اطاعت کرو",
  "Two commands": "دو احکام",
  "I ask no payment from you": "میں تم سے کوئی اجرت نہیں مانگتا",
  "No worldly motive": "کوئی دنیاوی مقصد نہیں",
  "My reward is only from the Lord of the worlds": "میرا اجر صرف رب العالمین کے ذمے ہے",
  "Seeking Allah's reward only": "صرف اللہ کا اجر چاہنا",
  "They said: Shall we believe you when the lowest follow you?": "انہوں نے کہا: ہم تجھ پر ایمان لائیں جبکہ تیرے پیرو کمتر لوگ ہیں؟",
  "Rejection based on followers' status": "پیروکاروں کی حیثیت کی بنا پر انکار",
  "He said: What knowledge do I have of what they did?": "اس نے کہا: مجھے کیا خبر کہ وہ کیا کرتے تھے؟",
  "Nuh doesn't judge backgrounds": "نوح پس منظر کا فیصلہ نہیں کرتے",
  "Their account is only with my Lord": "ان کا حساب صرف میرے رب کے پاس ہے",
  "Allah judges, not prophet": "فیصلہ اللہ کرتا ہے نبی نہیں",
  "And I will not drive away the believers": "اور میں مومنوں کو دھتکارنے والا نہیں",
  "Refusing to reject poor believers": "غریب مومنوں کو رد کرنے سے انکار",
  "I am only a clear warner": "میں تو صرف ایک واضح خبردار کرنے والا ہوں",
  "Role defined": "کردار کی وضاحت",
  "They said: If you don't stop, Nuh, you will be stoned": "انہوں نے کہا: اے نوح! اگر تو نہ رکا تو سنگسار کر دیا جائے گا",
  "Death threat": "موت کی دھمکی",
  "He said: My Lord, my people have denied me": "اس نے کہا: اے میرے رب، میری قوم نے مجھے جھٹلایا",
  "Nuh's complaint to Allah": "نوح کی اللہ سے شکایت",
  "So judge between me and them decisively": "تو میرے اور ان کے درمیان فیصلہ فرما دے",
  "Request for judgment": "فیصلے کی درخواست",
  "And save me and the believers with me": "اور مجھے اور میرے ساتھ کے مومنوں کو بچا لے",
  "Prayer for salvation": "نجات کی دعا",
  "So We saved him and those with him in the laden ship": "تو ہم نے اسے اور اس کے ساتھیوں کو بھری ہوئی کشتی میں بچا لیا",
  "Salvation in the Ark": "کشتی میں نجات",
  "Then We drowned the rest": "پھر ہم نے باقیوں کو غرق کر دیا",
  "Flood destroys deniers": "طوفان نے منکرین کو تباہ کیا",

  // hudStory
  "'Ad denied the messengers": "عاد نے رسولوں کو جھٹلایا",
  "Denial pattern continues": "انکار کا سلسلہ جاری",
  "When their brother Hud said: Will you not fear Allah?": "جب ان کے بھائی ہود نے کہا: کیا تم اللہ سے نہیں ڈرتے؟",
  "Hud from among them": "ہود ان ہی میں سے تھے",
  "Same claim as Nuh": "نوح جیسا ہی دعویٰ",
  "Same commands": "وہی احکام",
  "Do you build on every elevation a sign for amusement?": "کیا تم ہر اونچی جگہ بے فائدہ نشانی بناتے ہو؟",
  "Criticism of vanity projects": "فضول منصوبوں پر تنقید",
  "And take for yourselves palaces hoping to live forever?": "اور محلات بناتے ہو گویا ہمیشہ رہو گے؟",
  "Criticism of false immortality hopes": "جھوٹی امرِ دوام کی امید پر تنقید",
  "When you strike, you strike as tyrants": "اور جب تم پکڑتے ہو تو ظالموں کی طرح پکڑتے ہو",
  "Criticism of oppression": "ظلم پر تنقید",
  "Repeated call": "بار بار پکار",
  "Fear Him who provided you with what you know": "اس سے ڈرو جس نے تمہیں وہ دیا جو تم جانتے ہو",
  "Reminder of blessings": "نعمتوں کی یاد دہانی",
  "Provided you with livestock and children": "تمہیں مویشی اور اولاد عطا کیے",
  "Specific blessings": "مخصوص نعمتیں",
  "And gardens and springs": "اور باغات اور چشمے",
  "More blessings": "مزید نعمتیں",
  "I fear for you punishment of a great Day": "مجھے تمہارے بارے میں ایک بڑے دن کے عذاب کا ڈر ہے",
  "Warning of Judgment": "عذاب کی تنبیہ",
  "They said: Same to us whether you advise or not": "انہوں نے کہا: ہمارے لیے برابر ہے تو نصیحت کرے یا نہ کرے",
  "Complete indifference": "مکمل لاپرواہی",
  "This is nothing but custom of the ancients": "یہ تو بس پہلوں کی عادت ہے",
  "Dismissing as old tales": "پرانی کہانیاں کہہ کر ٹالنا",
  "And we will not be punished": "اور ہمیں عذاب نہیں ہوگا",
  "Denial of punishment": "عذاب کا انکار",
  "So they denied him and We destroyed them": "تو انہوں نے اسے جھٹلایا اور ہم نے انہیں ہلاک کر دیا",
  "Consequence of denial": "تکذیب کا نتیجہ",

  // salihStory
  "Thamud denied the messengers": "ثمود نے رسولوں کو جھٹلایا",
  "Another nation denies": "ایک اور قوم نے انکار کیا",
  "When their brother Salih said: Will you not fear Allah?": "جب ان کے بھائی صالح نے کہا: کیا تم اللہ سے نہیں ڈرتے؟",
  "Salih from among them": "صالح ان ہی میں سے تھے",
  "Will you be left secure in what is here?": "کیا تم یہاں کی چیزوں میں امن سے چھوڑ دیے جاؤ گے؟",
  "Challenge to their security": "ان کے تحفظ کو چیلنج",
  "In gardens and springs": "باغات اور چشموں میں",
  "Their comfortable life": "ان کی آسائشی زندگی",
  "And crops and date-palms with soft fruit": "اور کھیتیاں اور نرم پھلوں والی کھجوریں",
  "Agricultural blessings": "زرعی نعمتیں",
  "You carve from mountains homes skillfully": "اور تم پہاڑوں میں مہارت سے گھر تراشتے ہو",
  "Architectural achievements": "تعمیراتی کامیابیاں",
  "Do not obey the command of the transgressors": "حد سے گزرنے والوں کے حکم کی اطاعت نہ کرو",
  "Warning against corrupt leaders": "فاسد سرداروں کی اطاعت سے تنبیہ",
  "Who cause corruption and do not reform": "جو زمین میں فساد پھیلاتے ہیں اور اصلاح نہیں کرتے",
  "Description of transgressors": "حد سے گزرنے والوں کی تفصیل",
  "They said: You are but of the bewitched": "انہوں نے کہا: تو تو بس جادو زدہ ہے",
  "Accusation of being enchanted": "جادو زدہ ہونے کا الزام",
  "You are only a human like us": "تو بس ہمارے جیسا ایک انسان ہے",
  "Rejection based on humanity": "انسان ہونے کی بنا پر رد",
  "So bring a sign if you are truthful": "تو کوئی نشانی لا اگر تو سچا ہے",
  "Demand for proof": "ثبوت کا مطالبہ",
  "He said: This is a she-camel; she has a drink and you a drink on an appointed day": "اس نے کہا: یہ ایک اونٹنی ہے، ایک دن اس کے پینے کا اور ایک دن تمہارے پینے کا",
  "Miraculous she-camel": "معجزاتی اونٹنی",
  "Do not touch her with harm lest punishment of a great day seize you": "اسے برائی سے ہاتھ نہ لگانا ورنہ تمہیں بڑے دن کا عذاب پکڑ لے گا",
  "Warning about harming camel": "اونٹنی کو نقصان پہنچانے کی تنبیہ",
  "But they hamstrung her and became regretful": "لیکن انہوں نے اسے مار ڈالا اور پھر پچھتائے",
  "They killed it and regretted": "انہوں نے قتل کیا اور پچھتاوا ہوا",
  "So the punishment seized them": "تو عذاب نے انہیں پکڑ لیا",
  "Divine punishment came": "الٰہی عذاب آ گیا",

  // lutStory
  "The people of Lut denied the messengers": "قومِ لوط نے رسولوں کو جھٹلایا",
  "Pattern of denial": "انکار کا سلسلہ",
  "When their brother Lut said: Will you not fear Allah?": "جب ان کے بھائی لوط نے کہا: کیا تم اللہ سے نہیں ڈرتے؟",
  "Lut's call to his people": "لوط کی اپنی قوم کو دعوت",
  "Do you approach males of the worlds?": "کیا تم دنیا میں مردوں کے پاس جاتے ہو؟",
  "Condemning their sin": "ان کے گناہ کی مذمت",
  "And leave what your Lord created for you of your wives": "اور اپنی بیویوں کو چھوڑتے ہو جو تمہارے رب نے تمہارے لیے بنائی ہیں",
  "Abandoning natural way": "فطری طریقے کو چھوڑنا",
  "Rather, you are a transgressing people": "بلکہ تم حد سے گزرنے والی قوم ہو",
  "Judgment on them": "ان پر فیصلہ",
  "They said: If you don't stop, Lut, you will be expelled": "انہوں نے کہا: اے لوط اگر تو نہ رکا تو نکال دیا جائے گا",
  "Threat of expulsion": "جلاوطنی کی دھمکی",
  "He said: I am of those who detest your deed": "اس نے کہا: میں تمہارے عمل سے سخت نفرت رکھنے والوں میں سے ہوں",
  "Lut's disgust with their sin": "لوط کی ان کے گناہ سے نفرت",
  "My Lord, save me and my family from what they do": "اے میرے رب مجھے اور میرے گھر والوں کو ان کے عمل سے بچا",
  "Lut's prayer for salvation": "لوط کی نجات کی دعا",
  "So We saved him and his family, all": "تو ہم نے اسے اور اس کے گھر والوں کو بچا لیا",
  "Family saved": "خاندان بچا لیا گیا",
  "Except an old woman among those who remained": "سوائے ایک بوڑھی عورت کے جو پیچھے رہ جانے والوں میں تھی",
  "His wife stayed behind": "اس کی بیوی پیچھے رہ گئی",
  "Then We destroyed the others": "پھر ہم نے باقیوں کو تباہ کر دیا",
  "Destruction of sinners": "گناہگاروں کی تباہی",
  "And We rained upon them a rain": "اور ہم نے ان پر ایک بارش برسائی",
  "Rain of stones": "پتھروں کی بارش",
  "Evil was the rain of those warned": "بری تھی ان خبردار کیے گئے لوگوں کی بارش",
  "Terrible punishment": "ہولناک عذاب",

  // shuaybStory
  "The companions of the thicket denied the messengers": "جھاڑی والوں نے رسولوں کو جھٹلایا",
  "People of the woods/Midian": "جنگل والے / مدین کے لوگ",
  "When Shu'ayb said to them: Will you not fear Allah?": "جب شعیب نے ان سے کہا: کیا تم اللہ سے نہیں ڈرتے؟",
  "Shu'ayb's call": "شعیب کی پکار",
  "Give full measure and do not be of those who cause loss": "پورا ناپ دو اور گھاٹا دینے والوں میں نہ ہو",
  "Economic justice command": "معاشی انصاف کا حکم",
  "And weigh with a straight balance": "اور سیدھی ترازو سے تولو",
  "Fair weighing": "منصفانہ تول",
  "Do not deprive people of their due": "لوگوں کو ان کی چیزوں میں کمی نہ دو",
  "Rights of others": "دوسروں کے حقوق",
  "Do not commit abuse on earth, spreading corruption": "زمین میں فساد نہ پھیلاؤ",
  "Against corruption": "فساد کے خلاف",
  "Fear Him who created you and former generations": "اس سے ڈرو جس نے تمہیں اور پہلی نسلوں کو پیدا کیا",
  "Fear the Creator": "خالق سے ڈرو",
  "They said: You are but of the bewitched": "انہوں نے کہا: تو تو بس جادو زدہ ہے",
  "Same accusation as to Salih": "وہی الزام جو صالح پر لگایا",
  "You are only a human like us": "تو بس ہمارے جیسا ایک انسان ہے",
  "Rejection of human messenger": "انسان رسول کو رد کرنا",
  "We think you are of the liars": "ہمارا خیال ہے تو جھوٹوں میں سے ہے",
  "Accusation of lying": "جھوٹ کا الزام",
  "So drop upon us fragments from the sky": "تو ہم پر آسمان کے ٹکڑے گرا دے",
  "Mocking challenge": "مذاق اڑاتے ہوئے چیلنج",
  "If you are truthful": "اگر تو سچا ہے",
  "Demanding proof": "ثبوت مانگنا",
  "He said: My Lord knows best what you do": "اس نے کہا: میرا رب تمہارے اعمال سے خوب واقف ہے",
  "Shu'ayb's response": "شعیب کا جواب",
  "So they denied him and punishment of the Day of Shadow seized them": "تو انہوں نے اسے جھٹلایا اور سایے والے دن کے عذاب نے انہیں پکڑ لیا",
  "Punishment by shadow/cloud of fire": "آگ کے بادل/سائے کا عذاب",
  "It was punishment of a great day": "وہ ایک بڑے دن کا عذاب تھا",
  "Severity of their end": "ان کے انجام کی شدت",

  // quranRevelation
  "Indeed, it is revelation from the Lord of the worlds": "بے شک یہ رب العالمین کا نازل کردہ ہے",
  "Divine source affirmed": "الٰہی ماخذ کی تصدیق",
  "The Trustworthy Spirit brought it down": "اسے روحِ امین لے کر اترے",
  "Jibril as bearer": "جبریل بطور حامل",
  "Upon your heart so you may be a warner": "تمہارے دل پر تاکہ تم ڈرانے والوں میں سے ہو",
  "Revealed to Prophet's heart": "نبی ﷺ کے دل پر نازل ہوا",
  "In clear Arabic tongue": "واضح عربی زبان میں",
  "Language of revelation": "وحی کی زبان",
  "And it is in the scriptures of former peoples": "اور یہ پہلے لوگوں کی کتابوں میں بھی ہے",
  "Mentioned in previous books": "پچھلی کتابوں میں مذکور",
  "Was it not a sign that scholars of Israel knew it?": "کیا یہ ان کے لیے نشانی نہیں کہ بنی اسرائیل کے علماء اسے جانتے ہیں؟",
  "Jewish scholars recognize it": "یہودی علماء اسے پہچانتے ہیں",

  // nonArabMessenger
  "If We had revealed it to a non-Arab": "اگر ہم اسے کسی عجمی پر نازل کرتے",
  "Hypothetical scenario": "فرضی منظر نامہ",
  "And he recited it to them, they would not believe": "اور وہ انہیں پڑھ کر سناتا، وہ ایمان نہ لاتے",
  "They would still reject": "وہ پھر بھی رد کرتے",
  "Thus We inserted disbelief in hearts of criminals": "اسی طرح ہم نے مجرموں کے دلوں میں انکار ڈال دیا",
  "Denial rooted in heart": "انکار دل میں پیوست",
  "They will not believe until they see painful punishment": "وہ ایمان نہیں لائیں گے جب تک دردناک عذاب نہ دیکھ لیں",
  "Belief only when too late": "ایمان صرف اس وقت جب بہت دیر ہو چکی ہو",
  "It will come suddenly while they perceive not": "وہ اچانک آ جائے گا اور انہیں خبر بھی نہ ہوگی",
  "Punishment comes unexpectedly": "عذاب غیر متوقع طور پر آتا ہے",

  // warningAndDestruction
  "They will say: Can we be reprieved?": "وہ کہیں گے: کیا ہمیں مہلت دی جائے گی؟",
  "Desperate plea for delay": "مایوسانہ التجائے تاخیر",
  "Do they wish to hasten Our punishment?": "کیا یہ ہمارے عذاب کی جلدی کرتے ہیں؟",
  "Mocking those who challenge": "چیلنج کرنے والوں پر طنز",
  "Have you considered if We give them enjoyment for years": "کیا تو نے سوچا اگر ہم انہیں برسوں مزے دیں",
  "Even long life won't help": "لمبی عمر بھی کام نہ آئے گی",
  "Then what they were promised comes to them": "پھر ان سے وعدہ کی گئی چیز آ جائے",
  "Promise fulfilled eventually": "وعدہ بالآخر پورا ہوگا",
  "What will avail them what they enjoyed?": "ان کے فائدے میں سے جو کچھ بھی وہ مزے لوٹتے تھے کیا کام آئے گا؟",
  "Enjoyment won't save them": "عیش و آرام بچا نہیں سکے گا",
  "We did not destroy any city except it had warners": "ہم نے کوئی بستی ہلاک نہیں کی مگر اس کے خبردار کرنے والے تھے",
  "No destruction without warning": "تنبیہ کے بغیر کوئی تباہی نہیں",
  "As a reminder, and We were not unjust": "نصیحت کے طور پر، اور ہم ظالم نہیں تھے",
  "Divine justice in punishment": "عذاب میں الٰہی انصاف",

  // quranNotFromDevils
  "Devils did not bring it down": "اسے شیطانوں نے نازل نہیں کیا",
  "Refuting accusation": "الزام کی تردید",
  "It is not befitting for them, nor could they": "نہ یہ ان کے شایان ہے اور نہ وہ یہ کر سکتے ہیں",
  "Devils incapable": "شیطان قاصر ہیں",
  "They are barred from hearing": "وہ سننے سے روک دیے گئے ہیں",
  "Devils cannot access revelation": "شیطان وحی تک رسائی نہیں رکھتے",

  // warningAgainstIdolatry
  "Do not call with Allah another god": "اللہ کے ساتھ کسی اور معبود کو نہ پکار",
  "Warning against polytheism": "شرک سے تنبیہ",
  "Lest you be among the punished": "ورنہ عذاب پانے والوں میں سے ہو جائے گا",
  "Consequence of shirk": "شرک کا نتیجہ",
  "Warn your closest kindred": "اپنے قریب ترین رشتہ داروں کو خبردار کرو",
  "Start with family": "خاندان سے شروع کرو",
  "Lower your wing to believers who follow you": "اپنے پیروکار مومنوں کے لیے اپنا بازو جھکاؤ",
  "Be humble with followers": "پیروکاروں کے ساتھ تواضع",
  "If they disobey, say: I am free of what you do": "اگر نافرمانی کریں تو کہو: میں تمہارے اعمال سے بری ہوں",
  "Disassociation from sin": "گناہ سے براءت",
  "And rely on the Mighty, the Merciful": "اور غالب رحم والے پر بھروسہ کرو",
  "Trust in Allah": "اللہ پر توکل",
  "Who sees you when you stand": "جو تمہیں دیکھتا ہے جب تم کھڑے ہوتے ہو",
  "Allah sees your prayer": "اللہ تمہاری نماز دیکھتا ہے",
  "And your movement among those who prostrate": "اور تمہارا سجدہ کرنے والوں میں حرکت کرنا",
  "Allah sees all worship": "اللہ ساری عبادت دیکھتا ہے",
  "Indeed He is the Hearing, the Knowing": "بے شک وہ سننے والا جاننے والا ہے",
  "Divine attributes": "الٰہی صفات",

  // poetsContrast
  "Shall I tell you upon whom devils descend?": "کیا میں تمہیں بتاؤں شیطان کس پر اترتے ہیں؟",
  "Rhetorical question": "استفہامی سوال",
  "They descend upon every sinful liar": "وہ ہر جھوٹے گناہگار پر اترتے ہیں",
  "Devils inspire liars": "شیطان جھوٹوں کو سکھاتے ہیں",
  "They pass on what they hear, and most are liars": "وہ سنی سنائی بات پہنچاتے ہیں اور ان میں اکثر جھوٹے ہیں",
  "Soothsayers lie": "کاہنوں کا جھوٹ",
  "As for the poets, the deviators follow them": "اور شاعروں کی پیروی گمراہ لوگ کرتے ہیں",
  "Misguided follow poets": "گمراہ لوگ شاعروں کے پیچھے چلتے ہیں",
  "Do you not see that they wander in every valley?": "کیا تم نہیں دیکھتے کہ وہ ہر وادی میں بھٹکتے ہیں؟",
  "Poets' aimless wandering in fantasy": "شاعروں کا خیالی دنیا میں بے مقصد بھٹکنا",
  "And they say what they do not do": "اور وہ کہتے ہیں جو کرتے نہیں",
  "Poetry often insincere": "شاعری اکثر مخلصانہ نہیں ہوتی",

  // exceptedPoets
  "Except those who believe": "سوائے ان کے جو ایمان لائے",
  "Believing poets excepted": "ایمان والے شاعر مستثنیٰ",
  "And do righteous deeds": "اور نیک عمل کیے",
  "Righteous action required": "نیک اعمال ضروری ہیں",
  "And remember Allah often": "اور اللہ کو بکثرت یاد کیا",
  "Frequent remembrance": "کثرتِ ذکر",
  "And defend themselves after being wronged": "اور ظلم کے بعد اپنا دفاع کیا",
  "Defending Islam through poetry": "شاعری سے اسلام کا دفاع",
  "Those who wrong will know what return they will have": "ظالم جلد جان لیں گے کس کروٹ لوٹیں گے",
  "Warning to oppressors": "ظالموں کو تنبیہ",
};

console.log("Translation map for 026 ready with", Object.keys(URDU_TRANSLATIONS_026).length, "entries");
console.log("Use this script as a reference - actual file editing done via Edit tool");
