import fs from 'fs';

const file = 'src/data/treebank/ontology/043.js';
let content = fs.readFileSync(file, 'utf8');

const map = {
  // meaning field at top
  'ur: "The Gold Ornaments"': 'ur: "سونے کے زیورات"',

  // quranInArabic
  'ur: "Disconnected letters (Muqatta\'at) - part of Ha-Mim series"': 'ur: "حروفِ مقطعات - حوامیم سلسلے کا حصہ"',
  'ur: "By the clear Book"': 'ur: "واضح کتاب کی قسم"',
  'ur: "Oath by the Quran\'s clarity"': 'ur: "قرآن کی وضاحت کی قسم"',
  'ur: "Indeed, We have made it an Arabic Quran"': 'ur: "بے شک ہم نے اسے عربی قرآن بنایا"',
  'ur: "Quran revealed in Arabic for understanding"': 'ur: "قرآن سمجھنے کے لیے عربی میں نازل ہوا"',
  'ur: "That you might understand"': 'ur: "تاکہ تم سمجھو"',
  'ur: "Arabic chosen so Arabs comprehend"': 'ur: "عربی چنی گئی تاکہ عرب سمجھیں"',
  'ur: "And indeed it is, in the Mother of the Book with Us"': 'ur: "اور بے شک یہ ہمارے پاس ام الکتاب میں ہے"',
  'ur: "Quran\'s origin in the Preserved Tablet (Lawh Mahfuz)"': 'ur: "قرآن کی اصل لوحِ محفوظ میں ہے"',
  'ur: "Exalted and full of wisdom"': 'ur: "بلند مرتبہ اور حکمت سے بھرپور"',
  'ur: "The Quran\'s lofty and wise nature"': 'ur: "قرآن کی بلند اور حکمت آمیز فطرت"',
  'ur: "Should We turn away the Reminder from you?"': 'ur: "کیا ہم تم سے نصیحت پھیر لیں؟"',
  'ur: "Rhetorical - revelation continues despite rejection"': 'ur: "استفہامی - انکار کے باوجود وحی جاری رہتی ہے"',
  'ur: "Because you are a transgressing people"': 'ur: "اس لیے کہ تم حد سے بڑھنے والی قوم ہو"',
  'ur: "Transgression doesn\'t stop mercy"': 'ur: "سرکشی رحمت نہیں روکتی"',

  // previousProphetsRejected
  'ur: "And how many a prophet We sent among the former peoples"': 'ur: "اور پہلی قوموں میں ہم نے کتنے نبی بھیجے"',
  'ur: "Pattern of sending prophets"': 'ur: "نبیوں کو بھیجنے کا سلسلہ"',
  'ur: "And no prophet came to them except they mocked him"': 'ur: "اور ان کے پاس کوئی نبی نہیں آیا مگر انہوں نے اس کا مذاق اڑایا"',
  'ur: "Mockery is constant pattern"': 'ur: "مذاق اڑانا مستقل طریقہ ہے"',
  'ur: "So We destroyed those more powerful than them"': 'ur: "تو ہم نے ان سے زیادہ طاقتور لوگوں کو ہلاک کیا"',
  'ur: "Previous nations destroyed despite power"': 'ur: "پچھلی قومیں طاقت کے باوجود تباہ ہوئیں"',
  'ur: "And the example of the former peoples has passed"': 'ur: "اور پہلے لوگوں کی مثال گزر چکی ہے"',
  'ur: "Historical warning established"': 'ur: "تاریخی تنبیہ قائم ہو چکی"',

  // signsOfCreation
  'ur: "If you asked them who created heavens and earth"': 'ur: "اگر تم ان سے پوچھو کس نے آسمان و زمین بنائے"',
  'ur: "Even disbelievers acknowledge Creator"': 'ur: "کافر بھی خالق کو مانتے ہیں"',
  'ur: "They would say: The Mighty, the Knowing created them"': 'ur: "وہ کہیں گے: غالب جاننے والے نے انہیں بنایا"',
  'ur: "Innate acknowledgment of Allah"': 'ur: "اللہ کا فطری اعتراف"',
  'ur: "Who made the earth a bed for you"': 'ur: "جس نے زمین کو تمہارے لیے بچھونا بنایا"',
  'ur: "Earth spread out for living"': 'ur: "زمین رہنے کے لیے بچھائی گئی"',
  'ur: "And made for you therein pathways"': 'ur: "اور اس میں تمہارے لیے راستے بنائے"',
  'ur: "Roads and passages for travel"': 'ur: "سفر کے لیے سڑکیں اور راستے"',
  'ur: "That you may be guided"': 'ur: "تاکہ تم راستہ پاؤ"',
  'ur: "Physical and spiritual guidance"': 'ur: "جسمانی اور روحانی رہنمائی"',
  'ur: "Who sends down water from sky in measure"': 'ur: "جو آسمان سے اندازے سے پانی اتارتا ہے"',
  'ur: "Precise rainfall provision"': 'ur: "ناپی تُلی بارش کی فراہمی"',
  'ur: "And We revive thereby a dead land"': 'ur: "اور ہم اس سے مردہ زمین کو زندہ کرتے ہیں"',
  'ur: "Rain brings life - parallel to resurrection"': 'ur: "بارش زندگی لاتی ہے - قیامت کی مثال"',
  'ur: "Thus you will be brought forth"': 'ur: "اسی طرح تم نکالے جاؤ گے"',
  'ur: "Resurrection like land revival"': 'ur: "زمین کی بحالی جیسی قیامت"',

  // transportationBlessings
  'ur: "And Who created all the pairs"': 'ur: "اور جس نے تمام جوڑے بنائے"',
  'ur: "Male-female pairs in creation"': 'ur: "تخلیق میں نر و مادہ کے جوڑے"',
  'ur: "And made for you of ships and animals that you ride"': 'ur: "اور تمہارے لیے جہاز اور سواریاں بنائیں جن پر تم سوار ہو"',
  'ur: "Transportation provided by Allah"': 'ur: "اللہ کی فراہم کردہ سواریاں"',
  'ur: "That you may settle upon their backs"': 'ur: "تاکہ تم ان کی پشت پر بیٹھو"',
  'ur: "Ability to mount and ride"': 'ur: "سوار ہونے کی صلاحیت"',
  'ur: "Then remember the favor of your Lord when you settle upon it"': 'ur: "پھر جب اس پر بیٹھو تو اپنے رب کا احسان یاد کرو"',
  'ur: "Gratitude when mounting transport"': 'ur: "سواری پر بیٹھتے وقت شکر"',
  'ur: "Exalted is He who has subjected this to us"': 'ur: "پاک ہے وہ جس نے یہ ہمارے لیے مسخر کیا"',
  "ur: \"Travel supplication - recognizing Allah's control\"": 'ur: "سفر کی دعا - اللہ کے اختیار کا اعتراف"',
  'ur: "And we could not have subdued it ourselves"': 'ur: "اور ہم اسے خود قابو نہیں کر سکتے تھے"',
  "ur: \"Human inability without Allah's help\"": 'ur: "اللہ کی مدد کے بغیر انسانی بے بسی"',
  'ur: "And indeed we, to our Lord, will surely return"': 'ur: "اور بے شک ہم اپنے رب کی طرف لوٹنے والے ہیں"',
  'ur: "Remembering ultimate return while traveling"': 'ur: "سفر کے دوران آخری بازگشت یاد رکھنا"',

  // angelsAsFemales
  'ur: "And they have made for Him from His servants a portion"': 'ur: "اور انہوں نے اس کے بندوں میں سے اس کا حصہ بنایا"',
  'ur: "Attributing offspring to Allah"': 'ur: "اللہ کی طرف اولاد منسوب کرنا"',
  'ur: "Indeed, mankind is clearly ungrateful"': 'ur: "بے شک انسان کھلا ناشکرا ہے"',
  'ur: "Clear ingratitude in this claim"': 'ur: "اس دعوے میں واضح ناشکری"',
  'ur: "Has He taken from what He creates daughters?"': 'ur: "کیا اس نے اپنی مخلوق میں سے بیٹیاں لیں؟"',
  'ur: "Rhetorical - absurd claim"': 'ur: "استفہامِ انکاری - مضحکہ خیز دعویٰ"',
  'ur: "And chosen sons for you?"': 'ur: "اور تمہیں بیٹے چنے؟"',
  'ur: "Inconsistency in their own preference"': 'ur: "ان کی اپنی ترجیح میں تضاد"',
  'ur: "When one of them is given news of that which he attributes to the Most Merciful"': 'ur: "جب ان میں سے کسی کو اس کی خبر دی جائے جو وہ رحمٰن سے منسوب کرتا ہے"',
  'ur: "When told of a daughter..."': 'ur: "جب بیٹی کی خبر ملے..."',
  'ur: "His face becomes dark, and he suppresses grief"': 'ur: "اس کا چہرہ کالا پڑ جاتا ہے اور وہ غم دبائے رہتا ہے"',
  'ur: "Their own reaction to daughters"': 'ur: "بیٹیوں پر ان کا اپنا ردعمل"',
  'ur: "Is one raised in ornaments?"': 'ur: "کیا وہ جو زیورات میں پلے؟"',
  'ur: "Reference to feminine upbringing"': 'ur: "نسوانی پرورش کا حوالہ"',
  'ur: "And is unclear in dispute?"': 'ur: "اور بحث میں واضح نہیں؟"',
  'ur: "Stereotyping females - their own view"': 'ur: "عورتوں کے بارے میں دقیانوسی تصور - ان کا اپنا نظریہ"',
  'ur: "And they made the angels, who are servants of the Most Merciful, females"': 'ur: "اور انہوں نے فرشتوں کو جو رحمٰن کے بندے ہیں مادہ بنایا"',
  "ur: \"False claim about angels' gender\"": 'ur: "فرشتوں کی جنس کے بارے میں جھوٹا دعویٰ"',
  'ur: "Did they witness their creation?"': 'ur: "کیا وہ ان کی تخلیق کے وقت موجود تھے؟"',
  'ur: "No witness to make such claims"': 'ur: "ایسے دعوؤں کا کوئی گواہ نہیں"',
  'ur: "Their testimony will be recorded and they will be questioned"': 'ur: "ان کی گواہی لکھی جائے گی اور ان سے پوچھا جائے گا"',
  'ur: "Accountability for false claims"': 'ur: "جھوٹے دعوؤں کی جوابدہی"',

  // blindFollowingOfAncestors
  'ur: "And they say: If the Most Merciful had willed, we would not have worshipped them"': 'ur: "اور کہتے ہیں: اگر رحمٰن چاہتا تو ہم ان کی عبادت نہ کرتے"',
  'ur: "False fatalism to justify shirk"': 'ur: "شرک کا جواز پیش کرنے کے لیے جھوٹی تقدیر پرستی"',
  'ur: "They have no knowledge of that"': 'ur: "انہیں اس کا کوئی علم نہیں"',
  'ur: "Claim without evidence"': 'ur: "بغیر ثبوت کا دعویٰ"',
  'ur: "They are only guessing"': 'ur: "وہ صرف اٹکل لگاتے ہیں"',
  'ur: "Mere conjecture"': 'ur: "محض قیاس"',
  'ur: "Or have We given them a book before this?"': 'ur: "کیا ہم نے انہیں اس سے پہلے کوئی کتاب دی؟"',
  'ur: "No divine authority for their claims"': 'ur: "ان کے دعوؤں کا کوئی الٰہی سند نہیں"',
  'ur: "To which they are adhering?"': 'ur: "جسے وہ تھامے ہوئے ہیں؟"',
  'ur: "No scriptural basis"': 'ur: "کوئی کتابی بنیاد نہیں"',
  'ur: "Rather, they say: We found our fathers upon a religion"': 'ur: "بلکہ کہتے ہیں: ہم نے اپنے باپ دادا کو ایک مذہب پر پایا"',
  'ur: "Only basis is ancestral tradition"': 'ur: "واحد بنیاد آبائی روایت ہے"',
  'ur: "And we are guided by their footsteps"': 'ur: "اور ہم ان کے نقشِ قدم پر چل رہے ہیں"',
  'ur: "Blind following without thinking"': 'ur: "بغیر سوچے سمجھے اندھی تقلید"',
  'ur: "Similarly, We did not send before you any warner into a city"': 'ur: "اسی طرح تم سے پہلے کسی بستی میں کوئی خبردار کرنے والا نہیں بھیجا"',
  'ur: "Same pattern in all societies"': 'ur: "تمام معاشروں میں ایک ہی نمونہ"',
  'ur: "Except that its affluent said: We found our fathers upon a religion"': 'ur: "مگر اس کے خوشحالوں نے کہا: ہم نے اپنے باپ دادا کو ایک مذہب پر پایا"',
  'ur: "Wealthy elite uphold tradition"': 'ur: "دولتمند اشرافیہ روایت کو برقرار رکھتے ہیں"',
  'ur: "Say: Even if I brought you better guidance than that upon which you found your fathers?"': 'ur: "کہو: اگرچہ میں تمہیں اس سے بہتر ہدایت لاؤں جس پر تم نے اپنے باپ دادا کو پایا؟"',
  'ur: "Prophet offers superior guidance"': 'ur: "نبی بہتر ہدایت پیش کرتے ہیں"',
  'ur: "They said: Indeed we disbelieve in that with which you have been sent"': 'ur: "انہوں نے کہا: جو کچھ تم لے کر بھیجے گئے ہو ہم اس کے منکر ہیں"',
  'ur: "Rejection despite better alternative"': 'ur: "بہتر متبادل کے باوجود انکار"',
  'ur: "So We took retribution from them"': 'ur: "پس ہم نے ان سے بدلہ لیا"',
  'ur: "Consequence of rejection"': 'ur: "انکار کا نتیجہ"',
  'ur: "See how was the end of the deniers"': 'ur: "دیکھو جھٹلانے والوں کا انجام کیسا ہوا"',
  'ur: "Historical lesson"': 'ur: "تاریخی سبق"',

  // ibrahimMonotheism
  'ur: "And when Ibrahim said to his father and his people"': 'ur: "اور جب ابراہیم نے اپنے باپ اور قوم سے کہا"',
  "ur: \"Ibrahim's public declaration\"": 'ur: "ابراہیم کا علانیہ اعلان"',
  'ur: "Indeed, I am disassociated from that which you worship"': 'ur: "بے شک میں ان سے بیزار ہوں جن کی تم عبادت کرتے ہو"',
  'ur: "Clear disavowal of idolatry"': 'ur: "بت پرستی سے واضح بیزاری"',
  'ur: "Except He who created me"': 'ur: "مگر وہ جس نے مجھے پیدا کیا"',
  'ur: "Exception - worship only the Creator"': 'ur: "استثنا - صرف خالق کی عبادت"',
  'ur: "For indeed He will guide me"': 'ur: "کیونکہ بے شک وہ مجھے ہدایت دے گا"',
  'ur: "Trust in divine guidance"': 'ur: "الٰہی ہدایت پر بھروسا"',
  'ur: "And he made it a word remaining among his descendants"': 'ur: "اور اس نے اسے اپنی اولاد میں باقی رہنے والا کلمہ بنایا"',
  'ur: "La ilaha illallah as lasting legacy"': 'ur: "لا الٰہ الا اللہ بطور دائمی میراث"',
  'ur: "That they might return"': 'ur: "تاکہ وہ لوٹ آئیں"',
  'ur: "Hope for descendants to return to monotheism"': 'ur: "نسلوں کی توحید کی طرف واپسی کی امید"',
  'ur: "But I gave enjoyment to these and their fathers"': 'ur: "بلکہ میں نے ان کو اور ان کے باپ دادا کو عیش دیا"',
  "ur: \"Allah's patience with worldly enjoyment\"": 'ur: "دنیاوی عیش کے ساتھ اللہ کا صبر"',
  'ur: "Until the truth came to them and a clear Messenger"': 'ur: "یہاں تک کہ ان کے پاس حق آیا اور واضح رسول"',
  'ur: "Finally truth arrives with Muhammad"': 'ur: "آخرکار محمد ﷺ کے ساتھ حق آ گیا"',

  // rejectionOfMuhammad
  'ur: "And when the truth came to them, they said: This is magic"': 'ur: "اور جب حق ان کے پاس آیا تو کہا: یہ جادو ہے"',
  'ur: "Accusation of sorcery"': 'ur: "جادو کا الزام"',
  'ur: "And indeed we disbelieve in it"': 'ur: "اور بے شک ہم اس کے منکر ہیں"',
  'ur: "Open rejection"': 'ur: "کھلا انکار"',
  'ur: "And they said: Why was this Quran not sent down upon a great man from the two cities?"': 'ur: "اور کہا: یہ قرآن دونوں شہروں کے کسی بڑے آدمی پر کیوں نہیں اترا؟"',
  'ur: "Expecting revelation to wealthy leaders"': 'ur: "دولتمند سرداروں پر وحی کی توقع"',
  'ur: "Do they distribute the mercy of your Lord?"': 'ur: "کیا وہ تمہارے رب کی رحمت تقسیم کرتے ہیں؟"',
  "ur: \"They don't control who receives prophethood\"": 'ur: "وہ یہ اختیار نہیں رکھتے کہ نبوت کسے ملے"',
  'ur: "We have distributed among them their livelihood in worldly life"': 'ur: "ہم نے ان کے درمیان دنیاوی زندگی میں ان کی روزی تقسیم کی"',
  'ur: "Allah distributes provision and roles"': 'ur: "اللہ رزق اور کردار تقسیم کرتا ہے"',
  'ur: "And raised some of them above others in degrees"': 'ur: "اور بعض کو بعض پر درجات میں بلند کیا"',
  "ur: \"Hierarchy is Allah's design\"": 'ur: "درجہ بندی اللہ کا منصوبہ ہے"',
  'ur: "That they may make use of one another"': 'ur: "تاکہ وہ ایک دوسرے سے کام لیں"',
  'ur: "Interdependence in society"': 'ur: "معاشرے میں باہمی انحصار"',
  'ur: "And the mercy of your Lord is better than what they accumulate"': 'ur: "اور تمہارے رب کی رحمت اس سے بہتر ہے جو وہ جمع کرتے ہیں"',
  'ur: "Divine mercy exceeds worldly wealth"': 'ur: "الٰہی رحمت دنیاوی دولت سے بڑھ کر ہے"',

  // goldOrnamentsDevalued
  'ur: "And if it were not that people would become one community"': 'ur: "اور اگر یہ نہ ہوتا کہ لوگ ایک ہی قوم ہو جاتے"',
  'ur: "If not for test of faith..."': 'ur: "اگر ایمان کی آزمائش نہ ہوتی..."',
  'ur: "We would have made for disbelievers roofs of silver for their houses"': 'ur: "تو ہم کافروں کے گھروں کی چھتیں چاندی کی بنا دیتے"',
  'ur: "Allah could give disbelievers silver roofs"': 'ur: "اللہ کافروں کو چاندی کی چھتیں دے سکتا تھا"',
  'ur: "And stairways upon which to mount"': 'ur: "اور سیڑھیاں جن پر چڑھتے"',
  'ur: "Silver stairways for the disbelievers"': 'ur: "کافروں کے لیے چاندی کی سیڑھیاں"',
  'ur: "And for their houses doors and couches upon which to recline"': 'ur: "اور ان کے گھروں کے دروازے اور تخت جن پر ٹیک لگاتے"',
  'ur: "Luxurious doors and furniture"': 'ur: "عالیشان دروازے اور فرنیچر"',
  'ur: "And gold ornaments"': 'ur: "اور سونے کے زیورات"',
  'ur: "ZUKHRUF - the surah\'s namesake"': 'ur: "زخرف - سورت کا ہم نام"',
  'ur: "And all of that is nothing but enjoyment of worldly life"': 'ur: "اور یہ سب کچھ نہیں مگر دنیاوی زندگی کا عیش"',
  'ur: "Core message: gold/luxury is temporary"': 'ur: "بنیادی پیغام: سونا/عیش عارضی ہے"',
  'ur: "And the Hereafter with your Lord is for the righteous"': 'ur: "اور آخرت تمہارے رب کے ہاں متقیوں کے لیے ہے"',
  'ur: "Hereafter reserved for the God-conscious"': 'ur: "آخرت خدا ترس لوگوں کے لیے مخصوص ہے"',

  // satanAsCompanion
  'ur: "And whoever is blinded from remembrance of the Most Merciful"': 'ur: "اور جو رحمٰن کی یاد سے اندھا ہو جائے"',
  "ur: \"Turning away from Allah's remembrance\"": 'ur: "اللہ کی یاد سے اعراض"',
  'ur: "We appoint for him a devil"': 'ur: "ہم اس پر ایک شیطان مسلط کر دیتے ہیں"',
  'ur: "Satan assigned as companion"': 'ur: "شیطان بطور ساتھی مقرر"',
  'ur: "And he is to him a companion"': 'ur: "اور وہ اس کا ساتھی ہو جاتا ہے"',
  'ur: "Constant evil companionship"': 'ur: "مستقل بری ہمنشینی"',
  'ur: "And indeed, they avert them from the way"': 'ur: "اور بے شک وہ انہیں راستے سے ہٹاتے ہیں"',
  'ur: "Devils block the path"': 'ur: "شیاطین راستہ روکتے ہیں"',
  'ur: "While they think they are guided"': 'ur: "جبکہ وہ سمجھتے ہیں کہ وہ ہدایت پر ہیں"',
  'ur: "False sense of guidance"': 'ur: "ہدایت کا جھوٹا احساس"',
  'ur: "Until, when he comes to Us"': 'ur: "یہاں تک کہ جب وہ ہمارے پاس آئے"',
  'ur: "Moment of truth at judgment"': 'ur: "فیصلے کے وقت حقیقت کا لمحہ"',
  'ur: "He says: Oh, I wish between me and you was the distance of the two easts"': 'ur: "کہے گا: کاش میرے اور تیرے درمیان دونوں مشرقوں کی دوری ہوتی"',
  'ur: "Wishing maximum distance from satan"': 'ur: "شیطان سے زیادہ سے زیادہ فاصلے کی تمنا"',
  'ur: "What a wretched companion"': 'ur: "کیا برا ساتھی ہے"',
  'ur: "Satan revealed as worst companion"': 'ur: "شیطان بدترین ساتھی ثابت"',
  'ur: "And never will it benefit you that Day, when you have wronged, that you are sharing in punishment"': 'ur: "اور آج تمہیں فائدہ نہیں دے گا جبکہ تم نے ظلم کیا کہ تم سزا میں شریک ہو"',
  'ur: "Shared punishment offers no comfort"': 'ur: "مشترکہ سزا میں کوئی تسلی نہیں"',

  // prophetCannotGuideAll
  'ur: "Can you make the deaf hear?"': 'ur: "کیا تم بہروں کو سنا سکتے ہو؟"',
  'ur: "Rhetorical - spiritual deafness"': 'ur: "استفہامی - روحانی بہرا پن"',
  'ur: "Or guide the blind?"': 'ur: "یا اندھوں کو رہنمائی دے سکتے ہو؟"',
  'ur: "Spiritual blindness cannot be forced"': 'ur: "روحانی اندھا پن زبردستی دور نہیں ہو سکتا"',
  'ur: "And one who is in clear error?"': 'ur: "اور جو کھلی گمراہی میں ہو؟"',
  'ur: "Those in obvious misguidance"': 'ur: "واضح گمراہی والے"',
  'ur: "If We take you away, We will take retribution from them"': 'ur: "اگر ہم تمہیں لے جائیں تو ہم ان سے بدلہ لیں گے"',
  'ur: "Punishment will come regardless"': 'ur: "سزا ہر حال میں آئے گی"',
  'ur: "Or We will show you what We have promised them"': 'ur: "یا ہم تمہیں دکھائیں گے جو ہم نے ان سے وعدہ کیا"',
  'ur: "Prophet may witness their punishment"': 'ur: "نبی ﷺ شاید ان کی سزا دیکھیں"',
  'ur: "For indeed, We have power over them"': 'ur: "بے شک ہم ان پر قدرت رکھتے ہیں"',
  "ur: \"Allah's complete control\"": 'ur: "اللہ کا مکمل اختیار"',
  'ur: "So hold fast to that which is revealed to you"': 'ur: "پس جو تم پر وحی کیا گیا اسے مضبوطی سے تھامو"',
  'ur: "Command to adhere to revelation"': 'ur: "وحی پر قائم رہنے کا حکم"',
  'ur: "Indeed, you are upon a straight path"': 'ur: "بے شک تم صراطِ مستقیم پر ہو"',
  'ur: "Affirmation of correct guidance"': 'ur: "درست ہدایت کی تصدیق"',
  'ur: "And indeed, it is a reminder for you and your people"': 'ur: "اور بے شک یہ تمہارے اور تمہاری قوم کے لیے نصیحت ہے"',
  'ur: "Quran as honor for Arabs"': 'ur: "قرآن عربوں کے لیے باعثِ عزت"',
  'ur: "And you will be questioned"': 'ur: "اور تم سے پوچھا جائے گا"',
  'ur: "Accountability coming"': 'ur: "جوابدہی آنے والی ہے"',

  // allMessengersPreachedTawhid
  'ur: "And ask those We sent before you of Our messengers"': 'ur: "اور ان سے پوچھو جو ہم نے تم سے پہلے رسول بھیجے"',
  'ur: "Universal message of all prophets"': 'ur: "تمام انبیاء کا آفاقی پیغام"',
  'ur: "Did We make besides the Most Merciful gods to be worshipped?"': 'ur: "کیا ہم نے رحمٰن کے سوا معبود بنائے؟"',
  'ur: "No prophet endorsed polytheism"': 'ur: "کسی نبی نے شرک کی تائید نہیں کی"',

  // musaAndPharaoh
  'ur: "And We sent Musa with Our signs to Pharaoh and his establishment"': 'ur: "اور ہم نے موسیٰ کو اپنی نشانیوں کے ساتھ فرعون اور اس کے سرداروں کی طرف بھیجا"',
  'ur: "Musa sent to Pharaoh with miracles"': 'ur: "موسیٰ معجزات کے ساتھ فرعون کی طرف بھیجے گئے"',
  'ur: "He said: Indeed, I am a messenger of the Lord of the worlds"': 'ur: "اس نے کہا: بے شک میں رب العالمین کا رسول ہوں"',
  "ur: \"Musa's declaration of prophethood\"": 'ur: "موسیٰ کا اعلانِ نبوت"',
  'ur: "But when he brought them Our signs, they laughed at them"': 'ur: "مگر جب وہ ان کے پاس ہماری نشانیاں لائے تو انہوں نے ہنسی اڑائی"',
  'ur: "Mockery of divine signs"': 'ur: "الٰہی نشانیوں کا مذاق"',
  'ur: "And We showed them not a sign except it was greater than its sister"': 'ur: "اور ہم نے انہیں جو نشانی دکھائی وہ اپنی پچھلی سے بڑی تھی"',
  'ur: "Each sign more powerful than previous"': 'ur: "ہر نشانی پچھلی سے زیادہ طاقتور"',
  'ur: "And We seized them with punishment"': 'ur: "اور ہم نے انہیں عذاب سے پکڑا"',
  "ur: \"Divine punishment on Pharaoh's people\"": 'ur: "فرعون کی قوم پر الٰہی عذاب"',
  'ur: "That perhaps they might return"': 'ur: "شاید وہ باز آ جائیں"',
  'ur: "Punishment to encourage repentance"': 'ur: "توبہ کی ترغیب کے لیے سزا"',
  'ur: "And they said: O magician, invoke for us your Lord"': 'ur: "اور کہا: اے جادوگر اپنے رب سے ہمارے لیے دعا کر"',
  "ur: \"Pharaoh's people call Musa during affliction\"": 'ur: "مصیبت کے وقت فرعون کے لوگوں نے موسیٰ کو پکارا"',
  'ur: "By what He has promised you. Indeed, we will be guided"': 'ur: "اس کے عہد کے مطابق جو اس نے تم سے کیا۔ بے شک ہم ہدایت قبول کریں گے"',
  'ur: "False promise to believe"': 'ur: "ایمان لانے کا جھوٹا وعدہ"',
  'ur: "But when We removed from them the punishment, they broke their word"': 'ur: "مگر جب ہم نے ان سے عذاب ہٹایا تو انہوں نے عہد توڑ دیا"',
  'ur: "Breaking promise once saved"': 'ur: "بچ جانے پر وعدہ توڑنا"',

  // pharaohsArrogance
  'ur: "And Pharaoh called out among his people"': 'ur: "اور فرعون نے اپنی قوم میں پکارا"',
  "ur: \"Pharaoh's public proclamation\"": 'ur: "فرعون کا علانیہ اعلان"',
  'ur: "He said: O my people, does not the kingdom of Egypt belong to me?"': 'ur: "کہا: اے میری قوم کیا مصر کی بادشاہی میری نہیں؟"',
  'ur: "Boasting of Egyptian kingship"': 'ur: "مصری بادشاہت کا فخر"',
  'ur: "And these rivers flowing beneath me?"': 'ur: "اور یہ نہریں جو میرے نیچے بہتی ہیں؟"',
  "ur: \"Pride in Nile's abundance\"": 'ur: "نیل کی فراوانی پر فخر"',
  'ur: "Do you not see?"': 'ur: "کیا تم دیکھتے نہیں؟"',
  'ur: "Appealing to their senses"': 'ur: "ان کی عقل سے اپیل"',
  'ur: "Or am I not better than this one who is insignificant?"': 'ur: "یا میں بہتر نہیں ہوں اس سے جو حقیر ہے؟"',
  'ur: "Belittling Musa"': 'ur: "موسیٰ کی تحقیر"',
  'ur: "And can hardly express himself clearly"': 'ur: "اور بمشکل واضح بول سکتا ہے"',
  "ur: \"Mocking Musa's speech impediment\"": 'ur: "موسیٰ کی لکنت کا مذاق"',
  'ur: "Then why have not been placed upon him bracelets of gold?"': 'ur: "تو اس پر سونے کے کنگن کیوں نہیں ڈالے گئے؟"',
  'ur: "Demanding gold as proof of prophethood"': 'ur: "نبوت کے ثبوت کے طور پر سونے کا مطالبہ"',
  'ur: "Or come with him the angels accompanying?"': 'ur: "یا اس کے ساتھ فرشتے ساتھ آتے؟"',
  'ur: "Demanding angel escort"': 'ur: "فرشتوں کی ہمراہی کا مطالبہ"',
  'ur: "So he bluffed his people, and they obeyed him"': 'ur: "تو اس نے اپنی قوم کو ہلکا سمجھا اور انہوں نے اس کی اطاعت کی"',
  'ur: "Pharaoh manipulated masses"': 'ur: "فرعون نے عوام کو استعمال کیا"',
  'ur: "Indeed, they were a people defiantly disobedient"': 'ur: "بے شک وہ نافرمان قوم تھے"',
  'ur: "Root cause - disobedience"': 'ur: "بنیادی وجہ - نافرمانی"',
  'ur: "So when they angered Us, We took retribution from them"': 'ur: "پس جب انہوں نے ہمیں غضبناک کیا تو ہم نے ان سے بدلہ لیا"',
  'ur: "Divine anger triggered punishment"': 'ur: "الٰہی غضب نے سزا کو متحرک کیا"',
  'ur: "And drowned them all"': 'ur: "اور ان سب کو غرق کر دیا"',
  'ur: "Total destruction by drowning"': 'ur: "ڈوب کر مکمل تباہی"',
  'ur: "And We made them a precedent and an example for the later peoples"': 'ur: "اور ہم نے انہیں بعد والوں کے لیے نمونہ اور عبرت بنایا"',
  'ur: "Historical lesson for future"': 'ur: "آئندہ کے لیے تاریخی سبق"',

  // isaServantNotSon
  'ur: "And when the son of Mary was presented as an example"': 'ur: "اور جب ابنِ مریم کی مثال دی گئی"',
  'ur: "Isa cited in argument"': 'ur: "عیسیٰ کا بحث میں حوالہ"',
  'ur: "Immediately your people laughed aloud"': 'ur: "فوراً تمہاری قوم شور مچانے لگی"',
  'ur: "Quraysh mocked/disputed"': 'ur: "قریش نے مذاق اڑایا/تنازعہ کیا"',
  'ur: "And said: Are our gods better, or is he?"': 'ur: "اور کہا: ہمارے معبود بہتر ہیں یا وہ؟"',
  'ur: "Comparing Isa to idols"': 'ur: "عیسیٰ کا بتوں سے موازنہ"',
  'ur: "They did not present it except for argument"': 'ur: "انہوں نے یہ صرف جھگڑے کے لیے پیش کیا"',
  'ur: "Mere argumentation, not seeking truth"': 'ur: "محض بحث، حق کی تلاش نہیں"',
  'ur: "Rather, they are a quarrelsome people"': 'ur: "بلکہ وہ جھگڑالو قوم ہیں"',
  'ur: "Nature - contentious disputants"': 'ur: "فطرت - فتنہ انگیز بحث باز"',
  'ur: "He was not but a servant upon whom We bestowed favor"': 'ur: "وہ صرف ایک بندہ تھا جس پر ہم نے انعام کیا"',
  'ur: "CORE MESSAGE: Isa is servant (abd), not son"': 'ur: "بنیادی پیغام: عیسیٰ بندہ (عبد) ہیں بیٹے نہیں"',
  'ur: "And We made him an example for the Children of Israel"': 'ur: "اور ہم نے اسے بنی اسرائیل کے لیے نمونہ بنایا"',
  'ur: "Isa as sign for Israelites"': 'ur: "بنی اسرائیل کے لیے عیسیٰ بطور نشانی"',
  'ur: "And if We willed, We could make from among you angels succeeding on earth"': 'ur: "اور اگر ہم چاہتے تو تم میں سے زمین پر فرشتے جانشین بنا دیتے"',
  "ur: \"Allah's power to create differently\"": 'ur: "مختلف طریقے سے تخلیق کرنے کی اللہ کی قدرت"',
  'ur: "And indeed, he is a knowledge for the Hour"': 'ur: "اور بے شک وہ قیامت کی علامت ہے"',
  "ur: \"Isa's return as sign of Day of Judgment\"": 'ur: "یومِ قیامت کی نشانی کے طور پر عیسیٰ کی واپسی"',
  'ur: "So do not doubt it"': 'ur: "پس اس میں شک نہ کرو"',
  'ur: "No doubt about the Hour"': 'ur: "قیامت میں کوئی شک نہیں"',
  'ur: "And follow Me. This is a straight path"': 'ur: "اور میری پیروی کرو۔ یہ سیدھا راستہ ہے"',
  "ur: \"Call to follow Allah's guidance\"": 'ur: "اللہ کی ہدایت کی پیروی کی دعوت"',
  'ur: "And let not Satan avert you"': 'ur: "اور شیطان تمہیں نہ ہٹائے"',
  "ur: \"Warning against Satan's diversion\"": 'ur: "شیطان کے بہکاوے سے خبردار"',
  'ur: "Indeed, he is to you a clear enemy"': 'ur: "بے شک وہ تمہارا کھلا دشمن ہے"',
  "ur: \"Satan's open enmity\"": 'ur: "شیطان کی کھلی دشمنی"',

  // isasTeaching
  'ur: "And when Jesus brought clear proofs"': 'ur: "اور جب عیسیٰ واضح دلائل لائے"',
  'ur: "Isa came with evident signs"': 'ur: "عیسیٰ واضح نشانیاں لے کر آئے"',
  'ur: "He said: I have come to you with wisdom"': 'ur: "اس نے کہا: میں تمہارے پاس حکمت لایا ہوں"',
  'ur: "Isa brought divine wisdom"': 'ur: "عیسیٰ الٰہی حکمت لائے"',
  'ur: "And to make clear to you some of that over which you differ"': 'ur: "اور تاکہ تمہیں واضح کروں بعض وہ باتیں جن میں تم اختلاف کرتے ہو"',
  'ur: "Clarifying disputed matters"': 'ur: "متنازعہ معاملات کی وضاحت"',
  'ur: "So fear Allah and obey me"': 'ur: "پس اللہ سے ڈرو اور میری اطاعت کرو"',
  "ur: \"Isa's call to taqwa and obedience\"": 'ur: "عیسیٰ کی تقویٰ اور اطاعت کی دعوت"',
  'ur: "Indeed, Allah is my Lord and your Lord"': 'ur: "بے شک اللہ میرا اور تمہارا رب ہے"',
  'ur: "Isa affirms shared Lord"': 'ur: "عیسیٰ مشترک رب کی تصدیق کرتے ہیں"',
  'ur: "So worship Him. This is a straight path"': 'ur: "پس اسی کی عبادت کرو۔ یہ سیدھا راستہ ہے"',
  'ur: "Call to worship Allah alone"': 'ur: "صرف اللہ کی عبادت کی دعوت"',
  'ur: "But the parties differed among themselves"': 'ur: "مگر فرقوں نے آپس میں اختلاف کیا"',
  'ur: "Christians split into sects"': 'ur: "عیسائی فرقوں میں بٹ گئے"',
  'ur: "So woe to those who have wronged from punishment of a painful Day"': 'ur: "تو ہلاکت ہے ان ظالموں کے لیے دردناک دن کے عذاب سے"',
  'ur: "Warning to those who deviated"': 'ur: "بھٹکنے والوں کو تنبیہ"',

  // dayOfJudgment
  'ur: "Are they waiting except for the Hour to come upon them suddenly"': 'ur: "کیا یہ صرف اس کا انتظار کر رہے ہیں کہ قیامت اچانک آ جائے"',
  'ur: "Hour will come unexpectedly"': 'ur: "قیامت اچانک آئے گی"',
  'ur: "While they perceive not"': 'ur: "اور انہیں خبر بھی نہ ہو"',
  'ur: "Unaware of its timing"': 'ur: "اس کے وقت سے بے خبر"',
  'ur: "Close friends that Day will be enemies to each other"': 'ur: "اس دن قریبی دوست ایک دوسرے کے دشمن ہوں گے"',
  'ur: "False friendships exposed"': 'ur: "جھوٹی دوستیاں بے نقاب"',
  'ur: "Except for the righteous"': 'ur: "سوائے متقیوں کے"',
  'ur: "Only God-conscious maintain friendship"': 'ur: "صرف خدا ترس لوگوں کی دوستی قائم رہے گی"',

  // paradiseForRighteous
  'ur: "O My servants, no fear will there be concerning you this Day, nor will you grieve"': 'ur: "اے میرے بندو آج نہ تم پر کوئی خوف ہے اور نہ تم غمگین ہوگے"',
  'ur: "Divine assurance to believers"': 'ur: "مومنوں کو الٰہی تسلی"',
  'ur: "Those who believed in Our signs and were Muslims"': 'ur: "جو ہماری آیات پر ایمان لائے اور مسلمان تھے"',
  'ur: "Criteria: belief + submission"': 'ur: "معیار: ایمان + اسلام"',
  'ur: "Enter Paradise, you and your spouses, delighted"': 'ur: "جنت میں داخل ہو جاؤ تم اور تمہاری بیویاں خوشی خوشی"',
  'ur: "Entry with spouses in joy"': 'ur: "بیویوں کے ساتھ خوشی سے داخلہ"',
  'ur: "Circulated among them will be plates of gold and cups"': 'ur: "ان کے درمیان سونے کی طشتریاں اور پیالے گھمائے جائیں گے"',
  'ur: "Gold plates in Paradise - true gold"': 'ur: "جنت میں سونے کی طشتریاں - اصلی سونا"',
  'ur: "And therein is whatever souls desire and eyes delight in"': 'ur: "اور اس میں وہ سب ہے جو دل چاہیں اور آنکھوں کو بھلا لگے"',
  'ur: "All desires fulfilled"': 'ur: "تمام خواہشات پوری"',
  'ur: "And you will abide therein eternally"': 'ur: "اور تم اس میں ہمیشہ رہو گے"',
  'ur: "Eternal residence"': 'ur: "ابدی قیام"',
  'ur: "And that is Paradise which you are made to inherit for what you used to do"': 'ur: "اور یہ وہ جنت ہے جس کے تم اپنے اعمال کی وجہ سے وارث بنائے گئے"',
  'ur: "Paradise earned through deeds"': 'ur: "اعمال سے حاصل کی گئی جنت"',
  'ur: "For you therein is much fruit from which you will eat"': 'ur: "تمہارے لیے اس میں بہت سے پھل ہیں جن میں سے کھاؤ گے"',
  'ur: "Abundant fruits"': 'ur: "بکثرت پھل"',

  // criminalsInHell
  'ur: "Indeed, the criminals will be in punishment of Hell, abiding eternally"': 'ur: "بے شک مجرم جہنم کے عذاب میں ہمیشہ رہیں گے"',
  'ur: "Eternal punishment for criminals"': 'ur: "مجرموں کے لیے ابدی سزا"',
  'ur: "It will not be lightened for them"': 'ur: "ان سے ہلکا نہیں کیا جائے گا"',
  'ur: "No respite from punishment"': 'ur: "سزا سے کوئی مہلت نہیں"',
  'ur: "And they will be in despair therein"': 'ur: "اور وہ اس میں مایوس ہوں گے"',
  'ur: "Complete hopelessness"': 'ur: "مکمل مایوسی"',
  'ur: "And We did not wrong them, but they were the wrongdoers"': 'ur: "اور ہم نے ان پر ظلم نہیں کیا بلکہ وہ خود ظالم تھے"',
  'ur: "Self-inflicted through wrongdoing"': 'ur: "اپنے ظلم سے خود کو نقصان پہنچایا"',
  'ur: "And they will call: O Malik, let your Lord put an end to us"': 'ur: "اور پکاریں گے: اے مالک تمہارا رب ہمارا خاتمہ کر دے"',
  'ur: "Pleading for death to end suffering"': 'ur: "تکلیف ختم کرنے کے لیے موت کی التجا"',
  'ur: "He will say: Indeed, you will remain"': 'ur: "وہ کہے گا: بے شک تم یہیں رہو گے"',
  "ur: \"Malik's response - no escape\"": 'ur: "مالک کا جواب - کوئی فرار نہیں"',
  'ur: "We had certainly brought you the truth"': 'ur: "ہم تمہارے پاس حق لے آئے تھے"',
  'ur: "Truth was presented"': 'ur: "حق پیش کیا گیا تھا"',
  'ur: "But most of you were averse to the truth"': 'ur: "مگر تم میں سے اکثر حق سے نفرت کرتے تھے"',
  'ur: "Majority rejected truth"': 'ur: "اکثریت نے حق کو ٹھکرایا"',

  // secretPlotsExposed
  'ur: "Or have they devised an affair? Then We are devising"': 'ur: "کیا انہوں نے کوئی تدبیر کی ہے؟ تو ہم بھی تدبیر کرنے والے ہیں"',
  "ur: \"Allah's counter-plan\"": 'ur: "اللہ کی جوابی تدبیر"',
  'ur: "Or do they think that We hear not their secrets and private conversations?"': 'ur: "کیا وہ سمجھتے ہیں کہ ہم ان کی خفیہ باتیں اور سرگوشیاں نہیں سنتے؟"',
  'ur: "Allah hears all"': 'ur: "اللہ سب سنتا ہے"',
  'ur: "Yes, and Our messengers are with them recording"': 'ur: "ہاں اور ہمارے فرشتے ان کے پاس لکھ رہے ہیں"',
  'ur: "Angels record everything"': 'ur: "فرشتے سب کچھ لکھتے ہیں"',

  // noChildForAllah
  'ur: "Say: If the Most Merciful had a son"': 'ur: "کہو: اگر رحمٰن کا بیٹا ہوتا"',
  'ur: "Hypothetical argument"': 'ur: "فرضی دلیل"',
  'ur: "Then I would be the first of his worshippers"': 'ur: "تو میں سب سے پہلے اس کی عبادت کرنے والا ہوتا"',
  'ur: "Prophet would be first to worship if true"': 'ur: "اگر سچ ہوتا تو نبی ﷺ سب سے پہلے عبادت کرتے"',
  'ur: "Exalted is the Lord of the heavens and earth"': 'ur: "پاک ہے آسمانوں اور زمین کا رب"',
  'ur: "Allah transcends such claims"': 'ur: "اللہ ایسے دعوؤں سے پاک ہے"',
  'ur: "Lord of the Throne, above what they describe"': 'ur: "عرش کا مالک جو وہ بیان کرتے ہیں اس سے بالاتر"',
  'ur: "Beyond their false descriptions"': 'ur: "ان کے جھوٹے بیانات سے ماورا"',
  'ur: "So leave them to converse vainly and play"': 'ur: "پس انہیں چھوڑ دو کہ فضول باتیں کریں اور کھیلیں"',
  'ur: "Let them in their heedlessness"': 'ur: "انہیں ان کی غفلت میں رہنے دو"',
  'ur: "Until they meet their Day which they are promised"': 'ur: "جب تک وہ اپنے اس دن سے نہ مل لیں جس کا انہیں وعدہ دیا گیا"',
  'ur: "Until Judgment Day arrives"': 'ur: "جب تک قیامت نہ آ جائے"',

  // allahsSovereignty
  'ur: "And He is God in the heaven and God on the earth"': 'ur: "اور وہی آسمان میں معبود ہے اور زمین میں معبود"',
  'ur: "Sole deity in heaven and earth"': 'ur: "آسمان اور زمین میں واحد معبود"',
  'ur: "And He is the Wise, the Knowing"': 'ur: "اور وہ حکمت والا جاننے والا ہے"',
  'ur: "Wisdom and knowledge combined"': 'ur: "حکمت اور علم کا اجتماع"',
  'ur: "And blessed is He to whom belongs the dominion of heavens and earth"': 'ur: "اور بابرکت ہے وہ جس کی آسمانوں اور زمین کی بادشاہی ہے"',
  'ur: "All dominion belongs to Allah"': 'ur: "تمام بادشاہی اللہ کی ہے"',
  'ur: "And whatever is between them"': 'ur: "اور جو کچھ ان کے درمیان ہے"',
  'ur: "Everything in between included"': 'ur: "درمیان کی ہر چیز شامل"',
  'ur: "And with Him is knowledge of the Hour"': 'ur: "اور قیامت کا علم اسی کے پاس ہے"',
  'ur: "Only Allah knows the Hour"': 'ur: "قیامت کا وقت صرف اللہ جانتا ہے"',
  'ur: "And to Him you will be returned"': 'ur: "اور اسی کی طرف تم لوٹائے جاؤ گے"',
  'ur: "Final return to Allah"': 'ur: "اللہ کی طرف آخری بازگشت"',
  'ur: "And those they invoke besides Him do not possess intercession"': 'ur: "اور جنہیں وہ اس کے سوا پکارتے ہیں وہ سفارش کا اختیار نہیں رکھتے"',
  'ur: "False gods cannot intercede"': 'ur: "جھوٹے معبود سفارش نہیں کر سکتے"',
  'ur: "Except those who testify to the truth and know"': 'ur: "سوائے ان کے جو حق کی گواہی دیں اور جانتے ہوں"',
  'ur: "Only truthful witnesses can intercede"': 'ur: "صرف سچے گواہ سفارش کر سکتے ہیں"',
  'ur: "And if you asked them who created them, they would say: Allah"': 'ur: "اور اگر تم ان سے پوچھو کس نے انہیں پیدا کیا تو کہیں گے: اللہ"',
  'ur: "They acknowledge Creator yet worship others"': 'ur: "خالق کو مانتے ہیں پھر بھی اوروں کی عبادت کرتے ہیں"',
  'ur: "So how are they deluded?"': 'ur: "تو وہ کہاں بھٹک رہے ہیں؟"',
  'ur: "Illogic of their polytheism"': 'ur: "ان کے شرک کی بے عقلی"',

  // prophetsFrustration
  'ur: "And his saying: O my Lord, indeed these are a people who do not believe"': 'ur: "اور اس کا کہنا: اے میرے رب بے شک یہ ایسی قوم ہے جو ایمان نہیں لاتی"',
  "ur: \"Prophet's complaint to Allah\"": 'ur: "نبی ﷺ کی اللہ سے شکایت"',
  'ur: "So turn aside from them"': 'ur: "پس ان سے درگزر کرو"',
  'ur: "Command to overlook"': 'ur: "نظرانداز کرنے کا حکم"',
  'ur: "And say: Peace"': 'ur: "اور کہو: سلام"',
  'ur: "Respond with peace"': 'ur: "سلام سے جواب دو"',
  'ur: "For they are going to know"': 'ur: "کیونکہ عنقریب وہ جان لیں گے"',
  'ur: "Ultimate knowledge will come"': 'ur: "آخری علم آ کر رہے گا"',

  // thematicFlow
  'ur: "Ha-Mim, Quran in Arabic from Mother of Book, prophets mocked"': 'ur: "حم، ام الکتاب سے عربی قرآن، انبیاء کا مذاق"',
  'ur: "Earth, rain, transportation - blessings requiring gratitude"': 'ur: "زمین، بارش، سواری - شکر کی مستحق نعمتیں"',
  'ur: "False claim about angels, following ancestors blindly"': 'ur: "فرشتوں کے بارے میں جھوٹا دعویٰ، آباء کی اندھی تقلید"',
  "ur: \"Ibrahim's disavowal of idols, lasting word for descendants\"": 'ur: "ابراہیم کا بتوں سے اعلانِ برأت، اولاد کے لیے دائمی کلمہ"',
  "ur: \"Quraysh's objections, gold/ornaments devalued\"": 'ur: "قریش کے اعتراضات، سونے/زیورات کی بے قدری"',
  'ur: "Turning from Allah leads to satanic companionship"': 'ur: "اللہ سے اعراض شیطانی ہمنشینی کی طرف لے جاتا ہے"',
  "ur: \"Signs mocked, Pharaoh's arrogance, drowning\"": 'ur: "نشانیوں کا مذاق، فرعون کا تکبر، غرق"',
  'ur: "Isa is servant not son, his clear teaching"': 'ur: "عیسیٰ بندہ ہیں بیٹے نہیں، ان کی واضح تعلیم"',
  'ur: "Friends become enemies, Paradise for righteous, Hell for criminals"': 'ur: "دوست دشمن بنیں گے، متقیوں کے لیے جنت، مجرموں کے لیے جہنم"',
  'ur: "No child, universal Lord, Prophet\'s concern, peace"': 'ur: "کوئی اولاد نہیں، آفاقی رب، نبی کی فکر، سلامتی"',

  // uniqueInsight
  'ur: "The Surah of True vs False Gold"': 'ur: "اصلی بمقابلہ جعلی سونے کی سورت"',

  // linguisticFeatures
  'ur: "Gold ornaments/gilding"': 'ur: "سونے کے زیورات/ملمع"',
  'ur: "Word implies both beauty and deception - ornamental but superficial"': 'ur: "لفظ خوبصورتی اور فریب دونوں کا اظہار کرتا ہے - آرائشی مگر سطحی"',
  'ur: "Companion"': 'ur: "ساتھی"',
  'ur: "Intimate term for constant satanic presence - worse than temporary association"': 'ur: "مستقل شیطانی موجودگی کی قریبی اصطلاح - عارضی صحبت سے بدتر"',
  'ur: "Distance of two easts"': 'ur: "دونوں مشرقوں کا فاصلہ"',
  'ur: "Maximum conceivable distance - east of east"': 'ur: "ممکنہ زیادہ سے زیادہ فاصلہ"',
  'ur: "Insignificant/contemptible"': 'ur: "حقیر/ذلیل"',
  "ur: \"Pharaoh's dismissive term for Musa - ironic given outcome\"": 'ur: "فرعون کی موسیٰ کے لیے تحقیر آمیز اصطلاح - انجام دیکھتے ہوئے طنزیہ"',
  'ur: "Religion/way"': 'ur: "مذہب/طریقہ"',
  "ur: \"Same word for 'nation' and 'religion' - ancestors' religion becomes national identity\"": 'ur: "امت اور مذہب کے لیے ایک ہی لفظ - آباء کا مذہب قومی شناخت بن جاتا ہے"',
  'ur: "Ha-Mim"': 'ur: "حم"',
  'ur: "Part of 7 Ha-Mim surahs (40-46) - mysterious opening letters"': 'ur: "7 حوامیم سورتوں (40-46) کا حصہ - پراسرار ابتدائی حروف"',

  // scientificReferences
  'ur: "Analogy of dead land revived by rain parallels bodily resurrection"': 'ur: "بارش سے مردہ زمین کی بحالی جسمانی قیامت کی مثال ہے"',
  'ur: "Reference to male-female pairs across species"': 'ur: "تمام انواع میں نر مادہ جوڑوں کا حوالہ"',
  'ur: "Natural valleys and passes facilitating travel"': 'ur: "قدرتی وادیاں اور درے جو سفر آسان بناتے ہیں"',

  // historicalContext
  "ur: \"This Makki surah was revealed during intense opposition in Mecca when the Quraysh elite rejected Muhammad for not being a 'great man from the two cities' (Mecca or Taif). They expected prophethood to come with gold bracelets and angelic escorts - the same standard Pharaoh applied to Musa. The surah systematically dismantles their criteria: true worth is not measured by gold, lineage, or worldly status, but by relationship with Allah. The travel supplication (43:13-14) remains one of the most practiced Sunnah supplications to this day.\"": 'ur: "یہ مکی سورت مکہ میں شدید مخالفت کے دوران نازل ہوئی جب قریشی اشرافیہ نے محمد ﷺ کو اس لیے ٹھکرایا کہ وہ دونوں شہروں (مکہ یا طائف) کے کوئی بڑے آدمی نہیں۔ وہ نبوت کے ساتھ سونے کے کنگن اور فرشتوں کی ہمراہی کی توقع رکھتے تھے - وہی معیار جو فرعون نے موسیٰ پر لگایا۔ سورت منظم طریقے سے ان کے معیار کو ڈھاتی ہے: حقیقی قدر سونے، نسب یا دنیاوی حیثیت سے نہیں بلکہ اللہ سے تعلق سے ماپی جاتی ہے۔ سفر کی دعا (43:13-14) آج تک سب سے زیادہ پڑھی جانے والی مسنون دعاؤں میں سے ہے۔"',

  // uniqueInsight long
  "ur: \"Surah Az-Zukhruf derives its name from 'gold ornaments' (43:35), but its message is that gold/worldly luxury is worthless compared to divine guidance. The surah presents a powerful paradox: Allah could give disbelievers silver roofs, gold stairways, and luxurious furnishings - but all of it is merely 'enjoyment of worldly life' (متاع الحياة الدنيا). Meanwhile, the true gold - plates of gold (صحاف من ذهب, 43:71) - awaits believers in Paradise. The surah brilliantly connects three prophetic narratives: Ibrahim who established the lasting word of tawhid, Musa who faced Pharaoh's gold-obsessed arrogance (Pharaoh mocked Musa for not having gold bracelets, 43:53), and Isa who is a servant (عبد) despite those who elevated him to sonship. Each narrative dismantles false measures of worth - ancestral tradition, royal power, and divine sonship - and establishes the only true measure: servitude to Allah alone.\"": 'ur: "سورۃ الزخرف کا نام سونے کے زیورات (43:35) سے ماخوذ ہے مگر اس کا پیغام ہے کہ سونا/دنیاوی عیش الٰہی ہدایت کے مقابلے میں بے قیمت ہے۔ سورت ایک طاقتور تضاد پیش کرتی ہے: اللہ کافروں کو چاندی کی چھتیں، سونے کی سیڑھیاں اور عالیشان ساز و سامان دے سکتا تھا - مگر یہ سب محض متاع الحیاۃ الدنیا ہے۔ جبکہ اصلی سونا - سونے کی طشتریاں (صحاف من ذھب، 43:71) - جنت میں مومنوں کا انتظار کر رہا ہے۔ سورت تین نبوی بیانات کو شاندار طریقے سے جوڑتی ہے: ابراہیم جنہوں نے توحید کا دائمی کلمہ قائم کیا، موسیٰ جنہوں نے فرعون کے سونے سے مرعوب تکبر کا سامنا کیا (فرعون نے موسیٰ کا مذاق اڑایا کہ ان کے پاس سونے کے کنگن نہیں، 43:53)، اور عیسیٰ جو بندہ (عبد) ہیں باوجود ان کے جنہوں نے انہیں بیٹے کے درجے تک بلند کیا۔ ہر بیان قدر کے جھوٹے معیار - آبائی روایت، شاہی طاقت اور الٰہی بیٹا پن - کو ڈھاتا ہے اور واحد حقیقی معیار قائم کرتا ہے: صرف اللہ کی بندگی۔"',
};

let replaced = 0;
for (const [from, to] of Object.entries(map)) {
  if (content.includes(from)) {
    content = content.replaceAll(from, to);
    replaced++;
  }
}

fs.writeFileSync(file, content, 'utf8');
console.log(`043.js: Replaced ${replaced} translation keys`);
